/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __esm = (fn, res) => function __init() {
  return fn && (res = (0, fn[__getOwnPropNames(fn)[0]])(fn = 0)), res;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/ui/qrCodeModal.ts
var qrCodeModal_exports = {};
__export(qrCodeModal_exports, {
  QRCodeModal: () => QRCodeModal
});
var import_obsidian, QRCodeModal;
var init_qrCodeModal = __esm({
  "src/ui/qrCodeModal.ts"() {
    import_obsidian = require("obsidian");
    QRCodeModal = class extends import_obsidian.Modal {
      constructor(app) {
        super(app);
        this.qrcodeUrl = "";
        this.status = "wait";
        this.statusEl = null;
        this.qrContainer = null;
        this.onStatusChange = null;
      }
      setQRCode(url) {
        this.qrcodeUrl = url;
        this.renderQRCode();
      }
      setStatus(status) {
        this.status = status;
        this.renderStatus();
      }
      setOnStatusChange(callback) {
        this.onStatusChange = callback;
      }
      onOpen() {
        const { contentEl } = this;
        contentEl.empty();
        contentEl.addClass("wechat-sync-qrcode-modal");
        contentEl.createEl("h2", { text: "\u5FAE\u4FE1\u626B\u7801\u767B\u5F55" });
        this.qrContainer = contentEl.createDiv({
          cls: "wechat-sync-qrcode-container"
        });
        this.statusEl = contentEl.createDiv({
          cls: "wechat-sync-qrcode-status"
        });
        this.renderQRCode();
        this.renderStatus();
      }
      onClose() {
        this.contentEl.empty();
      }
      renderQRCode() {
        if (!this.qrContainer || !this.qrcodeUrl)
          return;
        this.qrContainer.empty();
        const linkEl = this.qrContainer.createEl("a", {
          href: this.qrcodeUrl,
          attr: { target: "_blank" }
        });
        linkEl.createEl("img", {
          attr: { src: this.qrcodeUrl, alt: "\u5FAE\u4FE1\u626B\u7801\u4E8C\u7EF4\u7801" },
          cls: "wechat-sync-qrcode-img"
        });
        this.qrContainer.createEl("p", {
          text: "\u70B9\u51FB\u56FE\u7247\u53EF\u5728\u6D4F\u89C8\u5668\u4E2D\u6253\u5F00\uFF0C\u7528\u624B\u673A\u5FAE\u4FE1\u626B\u7801",
          cls: "wechat-sync-qrcode-hint"
        });
      }
      renderStatus() {
        if (!this.statusEl)
          return;
        this.statusEl.empty();
        const statusMap = {
          wait: { text: "\u23F3 \u7B49\u5F85\u626B\u7801...", cls: "wechat-sync-status-wait" },
          scaned: {
            text: "\u{1F440} \u5DF2\u626B\u7801\uFF0C\u8BF7\u5728\u5FAE\u4FE1\u4E2D\u70B9\u51FB\u786E\u8BA4",
            cls: "wechat-sync-status-scaned"
          },
          confirmed: {
            text: "\u2705 \u767B\u5F55\u6210\u529F\uFF01",
            cls: "wechat-sync-status-confirmed"
          },
          expired: {
            text: "\u274C \u4E8C\u7EF4\u7801\u5DF2\u8FC7\u671F\uFF0C\u8BF7\u91CD\u65B0\u83B7\u53D6",
            cls: "wechat-sync-status-expired"
          }
        };
        const info = statusMap[this.status];
        this.statusEl.createEl("p", {
          text: info.text,
          cls: info.cls
        });
      }
    };
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WeChatSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian11 = require("obsidian");
var os2 = __toESM(require("os"));
var path4 = __toESM(require("path"));

// src/settings.ts
var import_obsidian2 = require("obsidian");
var WeChatSyncSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.connectionStatus = "not_configured";
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u5FAE\u4FE1\u540C\u6B65\u8BBE\u7F6E" });
    this.renderConnectionSection(containerEl);
    this.renderSyncSection(containerEl);
    this.renderMediaSection(containerEl);
    this.renderAdvancedSection(containerEl);
    this.renderUpdateSection(containerEl);
  }
  renderConnectionSection(containerEl) {
    containerEl.createEl("h3", { text: "Step 1: \u5FAE\u4FE1\u767B\u5F55" });
    const statusText = this.getConnectionStatusText();
    new import_obsidian2.Setting(containerEl).setName("\u8FDE\u63A5\u72B6\u6001").setDesc(statusText).addButton(
      (btn) => btn.setButtonText(this.plugin.ilinkAuth.isAuthenticated ? "\u91CD\u65B0\u767B\u5F55" : "\u626B\u7801\u767B\u5F55").setClass("mod-cta").onClick(async () => {
        await this.startQRLogin();
      })
    );
    if (this.plugin.ilinkAuth.isAuthenticated) {
      new import_obsidian2.Setting(containerEl).setName("\u5F53\u524D\u8D26\u53F7").setDesc(
        `Bot ID: ${this.plugin.ilinkAuth.currentIlinkUserId || "\u672A\u77E5"}`
      ).addButton(
        (btn) => btn.setButtonText("\u65AD\u5F00\u8FDE\u63A5").onClick(async () => {
          this.plugin.ilinkAuth.reset();
          await this.plugin.saveAuthData(null);
          this.plugin.statusBar.setStatus("not_configured");
          this.plugin.stopPoller();
          this.display();
        })
      );
    }
  }
  renderSyncSection(containerEl) {
    containerEl.createEl("h3", { text: "Step 2: \u540C\u6B65\u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("\u540C\u6B65\u76EE\u5F55").setDesc("\u5FAE\u4FE1\u6D88\u606F\u4FDD\u5B58\u5230 Obsidian \u7684\u76EE\u5F55").addText(
      (text) => text.setPlaceholder("WeChat Inbox").setValue(this.plugin.settings.syncFolder).onChange(async (value) => {
        this.plugin.settings.syncFolder = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u81EA\u52A8\u540C\u6B65").setDesc("\u81EA\u52A8\u63A5\u6536\u5FAE\u4FE1\u6D88\u606F\u5E76\u540C\u6B65\u5230 Obsidian").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSync).onChange(async (value) => {
        this.plugin.settings.autoSync = value;
        await this.plugin.saveSettings();
        this.plugin.resetAutoSyncTimer();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u540C\u6B65\u95F4\u9694\uFF08\u5206\u949F\uFF09").setDesc("\u81EA\u52A8\u540C\u6B65\u7684\u95F4\u9694\u65F6\u95F4\uFF08\u4EC5\u5728\u9700\u8981\u91CD\u8FDE\u65F6\u4F7F\u7528\uFF09").addSlider(
      (slider) => slider.setLimits(1, 60, 1).setValue(this.plugin.settings.syncIntervalMinutes).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.syncIntervalMinutes = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u540C\u6B65\u65B9\u5411").setDesc("\u9009\u62E9\u6D88\u606F\u540C\u6B65\u65B9\u5411").addDropdown(
      (dropdown) => dropdown.addOption("bidirectional", "\u53CC\u5411\u540C\u6B65").addOption("pull_only", "\u4EC5\u63A5\u6536\uFF08\u5FAE\u4FE1\u2192Obsidian\uFF09").addOption("push_only", "\u4EC5\u53D1\u9001\uFF08Obsidian\u2192\u5FAE\u4FE1\uFF09").setValue(this.plugin.settings.syncDirection).onChange(async (value) => {
        this.plugin.settings.syncDirection = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u51B2\u7A81\u7B56\u7565").setDesc("\u5F53\u540C\u4E00\u5185\u5BB9\u5728\u5FAE\u4FE1\u548C Obsidian \u90FD\u6709\u4FEE\u6539\u65F6").addDropdown(
      (dropdown) => dropdown.addOption("wechat_first", "\u5FAE\u4FE1\u4F18\u5148").addOption("local_first", "\u672C\u5730\u4F18\u5148").addOption("create_conflict", "\u521B\u5EFA\u51B2\u7A81\u526F\u672C").setValue(this.plugin.settings.conflictStrategy).onChange(async (value) => {
        this.plugin.settings.conflictStrategy = value;
        await this.plugin.saveSettings();
      })
    );
  }
  renderMediaSection(containerEl) {
    containerEl.createEl("h3", { text: "\u5A92\u4F53\u4E0E\u7FA4\u804A" });
    new import_obsidian2.Setting(containerEl).setName("\u540C\u6B65\u7FA4\u804A\u6D88\u606F").setDesc("\u63A5\u6536\u5E76\u540C\u6B65\u5FAE\u4FE1\u7FA4\u804A\u6D88\u606F").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableGroupSync).onChange(async (value) => {
        this.plugin.settings.enableGroupSync = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u4E0B\u8F7D\u5A92\u4F53\u6587\u4EF6").setDesc("\u81EA\u52A8\u4E0B\u8F7D\u5FAE\u4FE1\u4E2D\u7684\u56FE\u7247\u3001\u8BED\u97F3\u3001\u6587\u4EF6\u7B49\u5A92\u4F53").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableMediaDownload).onChange(async (value) => {
        this.plugin.settings.enableMediaDownload = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u5A92\u4F53\u6587\u4EF6\u76EE\u5F55").setDesc("\u5A92\u4F53\u6587\u4EF6\u4FDD\u5B58\u7684\u76EE\u5F55\uFF08\u76F8\u5BF9\u4E8E Vault \u6839\u76EE\u5F55\uFF09").addText(
      (text) => text.setPlaceholder("attachments/wechat").setValue(this.plugin.settings.mediaFolder).onChange(async (value) => {
        this.plugin.settings.mediaFolder = value;
        await this.plugin.saveSettings();
      })
    );
  }
  renderAdvancedSection(containerEl) {
    containerEl.createEl("h3", { text: "\u9AD8\u7EA7\u8BBE\u7F6E" });
    new import_obsidian2.Setting(containerEl).setName("\u65E5\u8BB0\u683C\u5F0F").setDesc("\u5FAE\u4FE1\u6D88\u606F\u6309\u65E5\u671F\u5F52\u6863\u7684\u6587\u4EF6\u540D\u683C\u5F0F").addText(
      (text) => text.setPlaceholder("YYYY-MM-DD").setValue(this.plugin.settings.dailyNoteFormat).onChange(async (value) => {
        this.plugin.settings.dailyNoteFormat = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u542F\u7528 Frontmatter").setDesc("\u5728\u7B14\u8BB0\u4E2D\u5199\u5165\u5FAE\u4FE1\u5143\u6570\u636E\uFF08msg_id\u3001session\u3001context_token \u7B49\uFF09").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableFrontmatter).onChange(async (value) => {
        this.plugin.settings.enableFrontmatter = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u53CC\u5411\u540C\u6B65").setDesc("\u76D1\u542C\u672C\u5730\u6587\u4EF6\u4FEE\u6539\u5E76\u81EA\u52A8\u540C\u6B65\u5230\u5FAE\u4FE1").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableBidirectionalSync).onChange(async (value) => {
        this.plugin.settings.enableBidirectionalSync = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u6D88\u606F\u5386\u53F2\u4E0A\u9650").setDesc("\u4FDD\u7559\u7684\u6700\u8FD1 context_token \u6570\u91CF\uFF08\u7528\u4E8E\u56DE\u590D\u6D88\u606F\uFF09").addSlider(
      (slider) => slider.setLimits(10, 500, 10).setValue(this.plugin.settings.maxMessageHistory).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.maxMessageHistory = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("\u542F\u52A8\u65F6\u68C0\u67E5\u66F4\u65B0").setDesc("Obsidian \u542F\u52A8\u65F6\u81EA\u52A8\u68C0\u67E5\u63D2\u4EF6\u66F4\u65B0").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.checkUpdateOnStartup).onChange(async (value) => {
        this.plugin.settings.checkUpdateOnStartup = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Gitee \u8BBF\u95EE\u4EE4\u724C").setDesc("\u7528\u4E8E\u8BBF\u95EE\u79C1\u6709\u4ED3\u5E93\u7684\u66F4\u65B0\uFF08\u53EF\u9009\uFF0C\u516C\u5F00\u4ED3\u5E93\u65E0\u9700\u586B\u5199\uFF09").addText((text) => {
      text.setPlaceholder("\u7559\u7A7A\u5219\u4F7F\u7528\u516C\u5F00\u8BBF\u95EE").setValue(this.plugin.settings.giteeAccessToken).onChange(async (value) => {
        this.plugin.settings.giteeAccessToken = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
  }
  renderUpdateSection(containerEl) {
    containerEl.createEl("h3", { text: "\u63D2\u4EF6\u66F4\u65B0" });
    const currentVersion = this.plugin.manifest.version;
    new import_obsidian2.Setting(containerEl).setName("\u5F53\u524D\u7248\u672C").setDesc(`v${currentVersion}`).addButton(
      (btn) => btn.setButtonText("\u68C0\u67E5\u66F4\u65B0").onClick(async () => {
        btn.setButtonText("\u68C0\u67E5\u4E2D...");
        btn.setDisabled(true);
        const info = await this.plugin.manualCheckUpdate();
        btn.setButtonText("\u68C0\u67E5\u66F4\u65B0");
        btn.setDisabled(false);
        if (info && info.hasUpdate) {
          this.display();
        }
      })
    );
    if (this.plugin.updateInfo && this.plugin.updateInfo.hasUpdate) {
      const info = this.plugin.updateInfo;
      new import_obsidian2.Setting(containerEl).setName(`\u{1F195} \u65B0\u7248\u672C\u53EF\u7528: v${info.latestVersion}`).setDesc(info.releaseNotes ? info.releaseNotes.slice(0, 200) : "\u6682\u65E0\u66F4\u65B0\u8BF4\u660E").addButton(
        (btn) => btn.setButtonText("\u7ACB\u5373\u66F4\u65B0").setClass("mod-cta").onClick(async () => {
          btn.setButtonText("\u66F4\u65B0\u4E2D...");
          btn.setDisabled(true);
          const success = await this.plugin.doUpdate();
          if (!success) {
            btn.setButtonText("\u7ACB\u5373\u66F4\u65B0");
            btn.setDisabled(false);
          }
        })
      );
    }
  }
  async startQRLogin() {
    try {
      const result = await this.plugin.ilinkAuth.fetchQRCode();
      const { QRCodeModal: QRCodeModal2 } = await Promise.resolve().then(() => (init_qrCodeModal(), qrCodeModal_exports));
      const modal = new QRCodeModal2(this.app);
      modal.setQRCode(result.qrcodeUrl);
      modal.open();
      const authResult = await this.plugin.ilinkAuth.loginWithPolling(
        result.qrcode,
        (status) => {
          modal.setStatus(status);
        }
      );
      modal.close();
      await this.plugin.saveAuthData(authResult);
      this.plugin.statusBar.setStatus("authed");
      await this.plugin.startPoller();
      new import_obsidian2.Notice("\u5FAE\u4FE1\u767B\u5F55\u6210\u529F\uFF01\u5DF2\u5F00\u59CB\u76D1\u542C\u6D88\u606F");
      this.display();
    } catch (e) {
      new import_obsidian2.Notice(`\u767B\u5F55\u5931\u8D25: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
  getConnectionStatusText() {
    if (this.plugin.ilinkAuth.isAuthenticated) {
      return "\u5DF2\u8FDE\u63A5\u5FAE\u4FE1\uFF0C\u6B63\u5728\u76D1\u542C\u6D88\u606F";
    }
    return "\u672A\u8FDE\u63A5\u5FAE\u4FE1\uFF0C\u8BF7\u70B9\u51FB\u626B\u7801\u767B\u5F55";
  }
};

// src/types.ts
var DEFAULT_SETTINGS = {
  syncFolder: "WeChat Inbox",
  autoSync: true,
  syncIntervalMinutes: 5,
  conflictStrategy: "create_conflict",
  syncDirection: "bidirectional",
  enableGroupSync: true,
  enableMediaDownload: true,
  mediaFolder: "attachments/wechat",
  dailyNoteFormat: "YYYY-MM-DD",
  checkUpdateOnStartup: true,
  giteeAccessToken: "",
  enableFrontmatter: true,
  enableBidirectionalSync: true,
  maxMessageHistory: 100
};

// src/ilink/ilinkHttp.ts
var https = __toESM(require("https"));
var http = __toESM(require("http"));
function nodeRequest(urlStr, method, headers, bodyStr, timeoutMs = 3e4) {
  const parsedUrl = new URL(urlStr);
  const isHttps = parsedUrl.protocol === "https:";
  const httpModule = isHttps ? https : http;
  const requestHeaders = { ...headers };
  if (bodyStr !== void 0) {
    requestHeaders["Content-Length"] = Buffer.byteLength(bodyStr).toString();
  }
  return new Promise((resolve, reject) => {
    const options = {
      hostname: parsedUrl.hostname,
      port: parsedUrl.port || (isHttps ? 443 : 80),
      path: parsedUrl.pathname + parsedUrl.search,
      method,
      headers: requestHeaders
    };
    const req = httpModule.request(options, (res) => {
      let data = "";
      res.on("data", (chunk) => {
        data += chunk.toString();
      });
      res.on("end", () => {
        resolve({
          status: res.statusCode || 0,
          data,
          headers: res.headers
        });
      });
    });
    req.on("error", (e) => {
      reject(e);
    });
    req.setTimeout(timeoutMs, () => {
      req.destroy();
      reject(new Error(`REQUEST_TIMEOUT_${timeoutMs}`));
    });
    if (bodyStr !== void 0) {
      req.write(bodyStr);
    }
    req.end();
  });
}
function parseJsonResponse(result) {
  try {
    return JSON.parse(result.data);
  } catch (e) {
    throw new Error(`\u89E3\u6790\u54CD\u5E94\u5931\u8D25 (HTTP ${result.status}): ${result.data.slice(0, 200)}`);
  }
}
function isTimeoutError(e, timeoutMs) {
  if (e instanceof Error) {
    if (timeoutMs) {
      return e.message === `REQUEST_TIMEOUT_${timeoutMs}`;
    }
    return e.message.startsWith("REQUEST_TIMEOUT_");
  }
  return false;
}

// src/ilink/ilinkAuth.ts
var BASE_URL = "https://ilinkai.weixin.qq.com";
var ILinkAuth = class {
  constructor() {
    this.baseUrl = BASE_URL;
    this.token = null;
    this.accountId = null;
    this.ilinkBotId = null;
    this.ilinkUserId = null;
  }
  get currentToken() {
    return this.token;
  }
  get currentAccountId() {
    return this.accountId;
  }
  get currentBaseUrl() {
    return this.baseUrl;
  }
  get currentIlinkUserId() {
    return this.ilinkUserId;
  }
  get isAuthenticated() {
    return this.token !== null;
  }
  async fetchQRCode() {
    const url = `${this.baseUrl}/ilink/bot/get_bot_qrcode?bot_type=3`;
    console.log("[WeChat Sync] \u83B7\u53D6\u4E8C\u7EF4\u7801:", url);
    const result = await nodeRequest(url, "GET", {});
    const data = parseJsonResponse(result);
    console.log("[WeChat Sync] \u4E8C\u7EF4\u7801\u54CD\u5E94: HTTP", result.status, JSON.stringify(data).slice(0, 200));
    if (!data.qrcode) {
      throw new Error(`\u83B7\u53D6\u4E8C\u7EF4\u7801\u5931\u8D25: ${JSON.stringify(data).slice(0, 200)}`);
    }
    return {
      qrcode: data.qrcode,
      qrcodeUrl: data.qrcode_img_content
    };
  }
  async pollQRStatus(qrcode) {
    const url = `${this.baseUrl}/ilink/bot/get_qrcode_status?qrcode=${encodeURIComponent(qrcode)}`;
    const result = await nodeRequest(url, "GET", {
      "iLink-App-ClientVersion": "1"
    });
    const data = parseJsonResponse(result);
    const status = data.status || "wait";
    if (status === "confirmed") {
      const token = data.bot_token || "";
      const ilinkBotId = data.ilink_bot_id || "";
      const accountId = ilinkBotId.replace(/@/g, "-").replace(/\./g, "-");
      const realBase = data.baseurl || this.baseUrl;
      const ilinkUserId = data.ilink_user_id || "";
      this.token = token;
      this.accountId = accountId;
      this.baseUrl = realBase;
      this.ilinkBotId = ilinkBotId;
      this.ilinkUserId = ilinkUserId;
      console.log("[WeChat Sync] \u767B\u5F55\u6210\u529F! accountId:", accountId, "baseUrl:", realBase);
      return {
        status: "confirmed",
        botToken: token,
        ilinkBotId,
        ilinkUserId,
        baseUrl: realBase
      };
    }
    return { status };
  }
  async loginWithPolling(qrcode, onStatusChange, timeoutMs = 48e4) {
    const deadline = Date.now() + timeoutMs;
    while (Date.now() < deadline) {
      try {
        const result = await this.pollQRStatus(qrcode);
        onStatusChange(result.status);
        if (result.status === "confirmed") {
          return {
            token: this.token,
            accountId: this.accountId,
            baseUrl: this.baseUrl,
            ilinkBotId: this.ilinkBotId,
            ilinkUserId: this.ilinkUserId
          };
        }
        if (result.status === "expired") {
          throw new Error("\u4E8C\u7EF4\u7801\u5DF2\u8FC7\u671F\uFF0C\u8BF7\u91CD\u65B0\u83B7\u53D6");
        }
      } catch (e) {
        if (e instanceof Error && e.message.includes("\u8FC7\u671F")) {
          throw e;
        }
        console.warn("[WeChat Sync] \u8F6E\u8BE2\u626B\u7801\u72B6\u6001\u5931\u8D25:", e);
      }
      await new Promise((resolve) => setTimeout(resolve, 1e3));
    }
    throw new Error("\u767B\u5F55\u8D85\u65F6\uFF088\u5206\u949F\uFF09\uFF0C\u8BF7\u91CD\u8BD5");
  }
  loadFromSaved(data) {
    this.token = data.token;
    this.accountId = data.accountId;
    this.baseUrl = data.baseUrl;
    this.ilinkBotId = data.ilinkBotId;
    this.ilinkUserId = data.ilinkUserId;
  }
  reset() {
    this.token = null;
    this.accountId = null;
    this.baseUrl = BASE_URL;
    this.ilinkBotId = null;
    this.ilinkUserId = null;
  }
};
function buildILinkHeaders(token) {
  const headers = {
    "Content-Type": "application/json",
    "AuthorizationType": "ilink_bot_token"
  };
  if (token) {
    headers["Authorization"] = `Bearer ${token}`;
  }
  const uin = Math.floor(Math.random() * 4294967295);
  headers["X-WECHAT-UIN"] = Buffer.from(String(uin)).toString("base64");
  return headers;
}

// src/ilink/ilinkPoller.ts
var LONG_POLL_TIMEOUT = 6e4;
var ILinkPoller = class {
  constructor() {
    this.running = false;
    this.buf = "";
    this.token = "";
    this.baseUrl = "";
    this.onMessage = null;
    this.onError = null;
    this.onStatusChange = null;
    this.failCount = 0;
    this.pollCount = 0;
    this.firstPollSuccess = false;
  }
  setMessageHandler(handler) {
    this.onMessage = handler;
  }
  setErrorHandler(handler) {
    this.onError = handler;
  }
  setStatusHandler(handler) {
    this.onStatusChange = handler;
  }
  async start(token, baseUrl) {
    var _a, _b, _c, _d, _e;
    if (this.running)
      return;
    this.token = token;
    this.baseUrl = baseUrl;
    this.running = true;
    this.failCount = 0;
    this.pollCount = 0;
    this.firstPollSuccess = false;
    this.buf = this.loadBuf();
    console.log("[WeChat Sync] \u8F6E\u8BE2\u542F\u52A8, baseUrl:", baseUrl, "token:", token ? `${token.slice(0, 10)}...` : "\u7A7A");
    (_a = this.onStatusChange) == null ? void 0 : _a.call(this, "polling");
    while (this.running) {
      try {
        const resp = await this.getUpdates(this.token, this.baseUrl, this.buf);
        this.pollCount++;
        if (!this.firstPollSuccess) {
          this.firstPollSuccess = true;
          console.log("[WeChat Sync] \u2705 \u9996\u6B21\u8F6E\u8BE2\u6210\u529F\uFF01\u8FDE\u63A5\u6B63\u5E38");
          (_b = this.onStatusChange) == null ? void 0 : _b.call(this, "connected");
        }
        if (this.pollCount % 20 === 1) {
          console.log(`[WeChat Sync] \u8F6E\u8BE2\u4E2D... (\u7B2C${this.pollCount}\u6B21, buf=${this.buf ? "\u6709\u6E38\u6807" : "\u7A7A\u6E38\u6807"})`);
        }
        if (resp.ret !== 0 && resp.errcode !== void 0 && resp.errcode !== 0) {
          const errMsg = `iLink\u9519\u8BEF: code=${resp.errcode} msg=${resp.errmsg || "\u672A\u77E5"}`;
          console.warn("[WeChat Sync]", errMsg);
          if (this.onError) {
            this.onError(new Error(errMsg));
          }
          if (resp.errcode === -14) {
            console.error("[WeChat Sync] \u4F1A\u8BDD\u8D85\u65F6(errcode=-14)\uFF0C\u9700\u8981\u91CD\u65B0\u767B\u5F55");
            (_c = this.onStatusChange) == null ? void 0 : _c.call(this, "session_expired");
            this.running = false;
            break;
          }
          await this.sleep(3e3);
          continue;
        }
        this.failCount = 0;
        if (resp.msgs && resp.msgs.length > 0) {
          console.log(`[WeChat Sync] \u{1F4E8} \u6536\u5230 ${resp.msgs.length} \u6761\u6D88\u606F!`);
          for (const msg of resp.msgs) {
            console.log(`[WeChat Sync] \u6D88\u606F: from=${msg.from_user_id}, type=${msg.message_type}, state=${msg.message_state}, hasContextToken=${!!msg.context_token}`);
            if (this.onMessage) {
              try {
                await this.onMessage(msg);
              } catch (e) {
                console.error("[WeChat Sync] \u6D88\u606F\u5904\u7406\u5931\u8D25:", e);
              }
            }
          }
        } else {
          if (this.pollCount <= 3) {
            console.log(`[WeChat Sync] \u7B2C${this.pollCount}\u6B21\u8F6E\u8BE2: \u65E0\u65B0\u6D88\u606F (ret=${resp.ret}, buf\u66F4\u65B0=${!!resp.get_updates_buf})`);
          }
        }
        if (resp.get_updates_buf) {
          this.buf = resp.get_updates_buf;
          this.saveBuf(this.buf);
        }
      } catch (e) {
        this.failCount++;
        const errMsg = e instanceof Error ? e.message : String(e);
        console.error(`[WeChat Sync] \u8F6E\u8BE2\u5931\u8D25 (${this.failCount}/5):`, errMsg);
        if (this.onError) {
          this.onError(new Error(`\u8F6E\u8BE2\u5931\u8D25 (${this.failCount}/5): ${errMsg}`));
        }
        if (this.failCount >= 5) {
          console.warn("[WeChat Sync] \u8FDE\u7EED\u5931\u8D255\u6B21\uFF0C\u7B49\u5F8530\u79D2\u540E\u91CD\u8BD5...");
          (_d = this.onStatusChange) == null ? void 0 : _d.call(this, "reconnecting");
          await this.sleep(3e4);
          this.failCount = 0;
        } else {
          await this.sleep(3e3);
        }
      }
    }
    console.log("[WeChat Sync] \u8F6E\u8BE2\u5DF2\u505C\u6B62");
    (_e = this.onStatusChange) == null ? void 0 : _e.call(this, "stopped");
  }
  stop() {
    console.log("[WeChat Sync] \u505C\u6B62\u8F6E\u8BE2...");
    this.running = false;
  }
  get isRunning() {
    return this.running;
  }
  async getUpdates(token, baseUrl, buf) {
    const url = `${baseUrl}/ilink/bot/getupdates`;
    const headers = buildILinkHeaders(token);
    const bodyObj = {
      get_updates_buf: buf,
      base_info: { channel_version: "1.0.3" }
    };
    try {
      const result = await nodeRequest(url, "POST", headers, JSON.stringify(bodyObj), LONG_POLL_TIMEOUT);
      return parseJsonResponse(result);
    } catch (e) {
      if (isTimeoutError(e, LONG_POLL_TIMEOUT)) {
        console.log("[WeChat Sync] \u957F\u8F6E\u8BE2\u8D85\u65F6(60s)\uFF0C\u6B63\u5E38\u91CD\u8BD5");
        return { ret: 0, msgs: [], get_updates_buf: buf };
      }
      throw e;
    }
  }
  loadBuf() {
    try {
      const fs3 = require("fs");
      const path5 = require("path");
      const os3 = require("os");
      const bufFile = path5.join(os3.homedir(), ".obsidian-wechat-sync-buf.txt");
      if (fs3.existsSync(bufFile)) {
        const buf = fs3.readFileSync(bufFile, "utf-8").trim();
        if (buf)
          console.log("[WeChat Sync] \u4ECE\u6E38\u6807\u6062\u590D:", buf.slice(0, 20) + "...");
        return buf;
      }
    } catch (e) {
      console.warn("[WeChat Sync] \u52A0\u8F7D\u6E38\u6807\u5931\u8D25:", e);
    }
    return "";
  }
  saveBuf(buf) {
    try {
      const fs3 = require("fs");
      const path5 = require("path");
      const os3 = require("os");
      const bufFile = path5.join(os3.homedir(), ".obsidian-wechat-sync-buf.txt");
      fs3.writeFileSync(bufFile, buf, "utf-8");
    } catch (e) {
      console.warn("[WeChat Sync] \u4FDD\u5B58\u6E38\u6807\u5931\u8D25:", e);
    }
  }
  sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
};

// src/ilink/ilinkSender.ts
var crypto = __toESM(require("crypto"));
var ILinkSender = class {
  constructor(token, baseUrl) {
    this.token = token;
    this.baseUrl = baseUrl;
  }
  updateToken(token) {
    this.token = token;
  }
  updateBaseUrl(baseUrl) {
    this.baseUrl = baseUrl;
  }
  async sendText(contextToken, text, toUserId) {
    const items = [
      { type: 1, text_item: { text } }
    ];
    return this.sendMessage(contextToken, items, 0, toUserId);
  }
  async sendMarkdown(contextToken, markdown, toUserId) {
    const items = [
      { type: 1, text_item: { text: markdown } }
    ];
    return this.sendMessage(contextToken, items, 1, toUserId);
  }
  async sendImage(contextToken, cdnUrl, aesKey, md5, fileSize, width, height, toUserId) {
    const items = [
      {
        type: 2,
        image_item: {
          cdn_url: cdnUrl,
          aes_key: aesKey,
          md5,
          file_size: fileSize,
          width,
          height
        }
      }
    ];
    return this.sendMessage(contextToken, items, 0, toUserId);
  }
  async sendFile(contextToken, cdnUrl, aesKey, md5, fileSize, fileName, toUserId) {
    const items = [
      {
        type: 4,
        file_item: {
          cdn_url: cdnUrl,
          aes_key: aesKey,
          md5,
          file_size: fileSize,
          file_name: fileName
        }
      }
    ];
    return this.sendMessage(contextToken, items, 0, toUserId);
  }
  async sendMessage(contextToken, itemList, contentType = 0, toUserId) {
    var _a;
    const url = `${this.baseUrl}/ilink/bot/sendmessage`;
    const headers = buildILinkHeaders(this.token);
    const clientId = `obsidian-${crypto.randomBytes(6).toString("hex")}`;
    const body = {
      msg: {
        from_user_id: "",
        to_user_id: toUserId || "",
        client_id: clientId,
        message_type: 2,
        message_state: 2,
        context_token: contextToken,
        item_list: itemList,
        content_type: contentType
      },
      base_info: { channel_version: "1.0.3" }
    };
    try {
      console.log("[WeChat Sync] \u53D1\u9001\u6D88\u606F\u5230:", url, "contextToken:", contextToken ? `${contextToken.slice(0, 10)}...` : "\u7A7A", "clientId:", clientId);
      const result = await nodeRequest(url, "POST", headers, JSON.stringify(body));
      if (result.status === 404) {
        console.error("[WeChat Sync] \u53D1\u9001\u63A5\u53E3404\uFF0C\u8BF7\u68C0\u67E5API\u8DEF\u5F84");
        return { ret: -1, errcode: -1, errmsg: `HTTP 404: \u63A5\u53E3\u4E0D\u5B58\u5728` };
      }
      const dataStr = result.data.trim();
      if (!dataStr || dataStr === "{}") {
        console.log("[WeChat Sync] \u53D1\u9001\u54CD\u5E94: HTTP", result.status, "\u7A7A\u54CD\u5E94\u4F53\uFF08\u53D1\u9001\u6210\u529F\uFF09");
        return { ret: 0 };
      }
      const data = parseJsonResponse(result);
      console.log("[WeChat Sync] \u53D1\u9001\u54CD\u5E94: HTTP", result.status, "ret=", data.ret, "errcode=", data.errcode, "errmsg=", (_a = data.errmsg) == null ? void 0 : _a.slice(0, 100));
      return data;
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      console.error("[WeChat Sync] \u53D1\u9001\u5931\u8D25:", msg);
      return {
        ret: -1,
        errcode: -1,
        errmsg: msg
      };
    }
  }
};

// src/ilink/ilinkCrypto.ts
var crypto2 = __toESM(require("crypto"));
var ILinkCrypto = class {
  static decryptCDNFile(encryptedBuffer, aesKeyHex) {
    const key = Buffer.from(aesKeyHex, "hex");
    const algorithm = "aes-256-cbc";
    const iv = key.slice(0, 16);
    const decipher = crypto2.createDecipheriv(algorithm, key, iv);
    decipher.setAutoPadding(true);
    const decrypted = Buffer.concat([
      decipher.update(encryptedBuffer),
      decipher.final()
    ]);
    return decrypted;
  }
  static calculateMD5(buffer) {
    return crypto2.createHash("md5").update(buffer).digest("hex");
  }
  static generateAESKey() {
    return crypto2.randomBytes(32).toString("hex");
  }
  static encryptFileForUpload(fileBuffer, aesKeyHex) {
    const key = Buffer.from(aesKeyHex, "hex");
    const algorithm = "aes-256-cbc";
    const iv = key.slice(0, 16);
    const cipher = crypto2.createCipheriv(algorithm, key, iv);
    cipher.setAutoPadding(true);
    return Buffer.concat([
      cipher.update(fileBuffer),
      cipher.final()
    ]);
  }
  static async downloadCDNFile(cdnUrl) {
    const https2 = require("https");
    const http2 = require("http");
    return new Promise((resolve, reject) => {
      const parsedUrl = new URL(cdnUrl);
      const isHttps = parsedUrl.protocol === "https:";
      const httpModule = isHttps ? https2 : http2;
      httpModule.get(cdnUrl, (res) => {
        const chunks = [];
        res.on("data", (chunk) => chunks.push(chunk));
        res.on("end", () => resolve(Buffer.concat(chunks)));
        res.on("error", reject);
      }).on("error", reject);
    });
  }
  static async downloadAndDecrypt(cdnUrl, aesKeyHex, expectedMd5) {
    const encrypted = await this.downloadCDNFile(cdnUrl);
    const decrypted = this.decryptCDNFile(encrypted, aesKeyHex);
    if (expectedMd5) {
      const actualMd5 = this.calculateMD5(decrypted);
      if (actualMd5 !== expectedMd5) {
        throw new Error(`MD5\u6821\u9A8C\u5931\u8D25: \u671F\u671B ${expectedMd5}, \u5B9E\u9645 ${actualMd5}`);
      }
    }
    return decrypted;
  }
};

// src/sync/messageHandler.ts
var import_obsidian3 = require("obsidian");
var MessageHandler = class {
  constructor(app, settings) {
    this.contextTokens = /* @__PURE__ */ new Map();
    this.onNewMessage = null;
    this.app = app;
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  setOnNewMessage(callback) {
    this.onNewMessage = callback;
  }
  async handleMessage(msg) {
    var _a, _b;
    if (msg.message_type !== 1)
      return;
    if (msg.message_state !== 0 && msg.message_state !== 2)
      return;
    if (!msg.item_list || msg.item_list.length === 0)
      return;
    if (msg.context_token) {
      this.storeContextToken(msg);
    }
    const isGroup = this.isGroupMessage(msg);
    if (isGroup && !this.settings.enableGroupSync)
      return;
    const text = this.extractText(msg);
    const hasMedia = this.hasMediaItems(msg);
    if (!text && !hasMedia)
      return;
    const fileName = this.generateFileName(msg);
    const folderPath = (0, import_obsidian3.normalizePath)(this.settings.syncFolder);
    if (!await this.app.vault.adapter.exists(folderPath)) {
      await this.app.vault.createFolder(folderPath);
    }
    const filePath2 = (0, import_obsidian3.normalizePath)(`${folderPath}/${fileName}.md`);
    const frontmatter = {
      wechat_msg_id: msg.message_id,
      wechat_from: msg.from_user_id,
      wechat_to: msg.to_user_id,
      wechat_time: msg.create_time_ms ? new Date(msg.create_time_ms).toISOString() : (/* @__PURE__ */ new Date()).toISOString(),
      wechat_session: msg.session_id,
      wechat_msg_type: (_b = (_a = msg.item_list) == null ? void 0 : _a[0]) == null ? void 0 : _b.type,
      wechat_sync_version: 1,
      wechat_last_sync: (/* @__PURE__ */ new Date()).toISOString(),
      wechat_context_token: msg.context_token,
      wechat_is_group: isGroup,
      wechat_group_id: isGroup ? msg.from_user_id : void 0
    };
    if (await this.app.vault.adapter.exists(filePath2)) {
      await this.appendToNote(filePath2, msg, frontmatter);
    } else {
      const mediaResults = await this.downloadMediaItems(msg);
      const content = this.buildNoteContent(msg, frontmatter, mediaResults);
      await this.app.vault.create(filePath2, content);
    }
    if (this.onNewMessage) {
      this.onNewMessage(msg);
    }
  }
  extractText(msg) {
    if (!msg.item_list)
      return "";
    return msg.item_list.filter((item) => item.type === 1 && item.text_item).map((item) => item.text_item.text).join("\n");
  }
  isGroupMessage(msg) {
    var _a;
    return !!((_a = msg.from_user_id) == null ? void 0 : _a.includes("@chatroom"));
  }
  getLatestContextToken(userId) {
    if (userId) {
      return this.contextTokens.get(userId) || null;
    }
    let latest = null;
    for (const entry of this.contextTokens.values()) {
      if (!latest || entry.timestamp > latest.timestamp) {
        latest = entry;
      }
    }
    return latest;
  }
  getContextTokenForSession(sessionId) {
    for (const entry of this.contextTokens.values()) {
      if (entry.sessionId === sessionId)
        return entry;
    }
    return null;
  }
  storeContextToken(msg) {
    const key = msg.from_user_id || msg.session_id || "default";
    const text = this.extractText(msg);
    this.contextTokens.set(key, {
      contextToken: msg.context_token,
      fromUserId: msg.from_user_id || "",
      sessionId: msg.session_id || "",
      timestamp: msg.create_time_ms || Date.now(),
      lastMessage: text.slice(0, 100)
    });
    if (this.contextTokens.size > this.settings.maxMessageHistory) {
      let oldest = null;
      let oldestTime = Infinity;
      for (const [k, v] of this.contextTokens) {
        if (v.timestamp < oldestTime) {
          oldestTime = v.timestamp;
          oldest = k;
        }
      }
      if (oldest)
        this.contextTokens.delete(oldest);
    }
  }
  hasMediaItems(msg) {
    if (!msg.item_list)
      return false;
    return msg.item_list.some(
      (item) => item.type === 2 || item.type === 3 || item.type === 4 || item.type === 5
    );
  }
  generateFileName(msg) {
    var _a;
    const date = msg.create_time_ms ? new Date(msg.create_time_ms) : /* @__PURE__ */ new Date();
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    const format = this.settings.dailyNoteFormat.replace("YYYY", String(year)).replace("MM", month).replace("DD", day);
    const isGroup = this.isGroupMessage(msg);
    if (isGroup) {
      const groupId = ((_a = msg.from_user_id) == null ? void 0 : _a.replace("@chatroom", "")) || "\u7FA4";
      return `\u5FAE\u4FE1\u7FA4-${groupId}-${format}`;
    }
    return `\u5FAE\u4FE1-${format}`;
  }
  async downloadMediaItems(msg) {
    const results = /* @__PURE__ */ new Map();
    if (!this.settings.enableMediaDownload || !msg.item_list)
      return results;
    const mediaFolder = (0, import_obsidian3.normalizePath)(this.settings.mediaFolder);
    if (!await this.app.vault.adapter.exists(mediaFolder)) {
      await this.app.vault.createFolder(mediaFolder);
    }
    for (let i = 0; i < msg.item_list.length; i++) {
      const item = msg.item_list[i];
      try {
        if (item.type === 2 && item.image_item) {
          const localPath = await this.downloadImage(item.image_item, msg.message_id || Date.now(), i);
          if (localPath)
            results.set(i, localPath);
        } else if (item.type === 4 && item.file_item) {
          const localPath = await this.downloadFile(item.file_item, msg.message_id || Date.now());
          if (localPath)
            results.set(i, localPath);
        } else if (item.type === 3 && item.voice_item) {
          const localPath = await this.downloadVoice(item.voice_item, msg.message_id || Date.now());
          if (localPath)
            results.set(i, localPath);
        } else if (item.type === 5 && item.video_item) {
          const localPath = await this.downloadVideo(item.video_item, msg.message_id || Date.now());
          if (localPath)
            results.set(i, localPath);
        }
      } catch (e) {
        console.error("[WeChat Sync] \u5A92\u4F53\u4E0B\u8F7D\u5931\u8D25:", e);
      }
    }
    return results;
  }
  async downloadImage(imageItem, msgId, index) {
    try {
      const decrypted = await ILinkCrypto.downloadAndDecrypt(
        imageItem.cdn_url,
        imageItem.aes_key,
        imageItem.md5
      );
      const fileName = `img-${msgId}-${index}.jpg`;
      const localPath = (0, import_obsidian3.normalizePath)(`${this.settings.mediaFolder}/${fileName}`);
      await this.app.vault.adapter.writeBinary(localPath, decrypted.buffer);
      return localPath;
    } catch (e) {
      console.error("[WeChat Sync] \u56FE\u7247\u4E0B\u8F7D\u5931\u8D25:", e);
      return null;
    }
  }
  async downloadFile(fileItem, msgId) {
    try {
      const decrypted = await ILinkCrypto.downloadAndDecrypt(
        fileItem.cdn_url,
        fileItem.aes_key,
        fileItem.md5
      );
      const fileName = `file-${msgId}-${fileItem.file_name}`;
      const localPath = (0, import_obsidian3.normalizePath)(`${this.settings.mediaFolder}/${fileName}`);
      await this.app.vault.adapter.writeBinary(localPath, decrypted.buffer);
      return localPath;
    } catch (e) {
      console.error("[WeChat Sync] \u6587\u4EF6\u4E0B\u8F7D\u5931\u8D25:", e);
      return null;
    }
  }
  async downloadVoice(voiceItem, msgId) {
    try {
      const decrypted = await ILinkCrypto.downloadAndDecrypt(
        voiceItem.cdn_url,
        voiceItem.aes_key,
        voiceItem.md5
      );
      const fileName = `voice-${msgId}.silk`;
      const localPath = (0, import_obsidian3.normalizePath)(`${this.settings.mediaFolder}/${fileName}`);
      await this.app.vault.adapter.writeBinary(localPath, decrypted.buffer);
      return localPath;
    } catch (e) {
      console.error("[WeChat Sync] \u8BED\u97F3\u4E0B\u8F7D\u5931\u8D25:", e);
      return null;
    }
  }
  async downloadVideo(videoItem, msgId) {
    try {
      const decrypted = await ILinkCrypto.downloadAndDecrypt(
        videoItem.cdn_url,
        videoItem.aes_key,
        videoItem.md5
      );
      const fileName = `video-${msgId}.mp4`;
      const localPath = (0, import_obsidian3.normalizePath)(`${this.settings.mediaFolder}/${fileName}`);
      await this.app.vault.adapter.writeBinary(localPath, decrypted.buffer);
      return localPath;
    } catch (e) {
      console.error("[WeChat Sync] \u89C6\u9891\u4E0B\u8F7D\u5931\u8D25:", e);
      return null;
    }
  }
  buildNoteContent(msg, frontmatter, mediaResults) {
    var _a, _b;
    const lines = [];
    if (this.settings.enableFrontmatter) {
      lines.push("---");
      for (const [key, value] of Object.entries(frontmatter)) {
        if (value !== void 0 && value !== null) {
          lines.push(`${key}: ${typeof value === "string" ? `"${value}"` : value}`);
        }
      }
      lines.push("---");
      lines.push("");
    }
    const isGroup = this.isGroupMessage(msg);
    if (isGroup) {
      const sender = this.extractSenderFromGroup(msg);
      const timeStr = this.formatTime(msg.create_time_ms);
      lines.push(`**${timeStr}** ${sender}:`);
      lines.push("");
    }
    if (msg.item_list) {
      for (let i = 0; i < msg.item_list.length; i++) {
        const item = msg.item_list[i];
        const mediaPath = mediaResults.get(i);
        switch (item.type) {
          case 1:
            if (item.text_item) {
              lines.push(item.text_item.text);
              lines.push("");
            }
            break;
          case 2:
            if (mediaPath) {
              lines.push(`![\u5FAE\u4FE1\u56FE\u7247](${mediaPath})`);
            } else {
              lines.push(`![\u5FAE\u4FE1\u56FE\u7247](placeholder)`);
            }
            lines.push("");
            break;
          case 3:
            if (mediaPath) {
              lines.push(`\u{1F3B5} [\u8BED\u97F3\u6D88\u606F](${mediaPath})`);
            } else {
              lines.push(`*\u8BED\u97F3\u6D88\u606F*`);
            }
            lines.push("");
            break;
          case 4:
            if (mediaPath) {
              lines.push(`\u{1F4CE} [${((_a = item.file_item) == null ? void 0 : _a.file_name) || "\u6587\u4EF6"}](${mediaPath})`);
            } else {
              lines.push(`\u{1F4CE} ${((_b = item.file_item) == null ? void 0 : _b.file_name) || "\u6587\u4EF6"}`);
            }
            lines.push("");
            break;
          case 5:
            if (mediaPath) {
              lines.push(`\u{1F3AC} [\u89C6\u9891](${mediaPath})`);
            } else {
              lines.push(`\u{1F3AC} \u89C6\u9891`);
            }
            lines.push("");
            break;
        }
      }
    }
    return lines.join("\n");
  }
  async appendToNote(filePath2, msg, frontmatter) {
    var _a, _b;
    const file = this.app.vault.getAbstractFileByPath(filePath2);
    if (!(file instanceof import_obsidian3.TFile))
      return;
    const existing = await this.app.vault.read(file);
    const mediaResults = await this.downloadMediaItems(msg);
    const timeStr = this.formatTime(msg.create_time_ms);
    const isGroup = this.isGroupMessage(msg);
    const sender = isGroup ? this.extractSenderFromGroup(msg) : msg.from_user_id || "\u6211";
    const appendLines = [];
    appendLines.push(`---`);
    appendLines.push(`**${timeStr}** ${sender}:`);
    appendLines.push("");
    if (msg.item_list) {
      for (let i = 0; i < msg.item_list.length; i++) {
        const item = msg.item_list[i];
        const mediaPath = mediaResults.get(i);
        switch (item.type) {
          case 1:
            if (item.text_item) {
              appendLines.push(item.text_item.text);
            }
            break;
          case 2:
            if (mediaPath) {
              appendLines.push(`![\u5FAE\u4FE1\u56FE\u7247](${mediaPath})`);
            } else {
              appendLines.push(`![\u5FAE\u4FE1\u56FE\u7247](placeholder)`);
            }
            break;
          case 3:
            if (mediaPath) {
              appendLines.push(`\u{1F3B5} [\u8BED\u97F3\u6D88\u606F](${mediaPath})`);
            } else {
              appendLines.push(`*\u8BED\u97F3\u6D88\u606F*`);
            }
            break;
          case 4:
            if (mediaPath) {
              appendLines.push(`\u{1F4CE} [${((_a = item.file_item) == null ? void 0 : _a.file_name) || "\u6587\u4EF6"}](${mediaPath})`);
            } else {
              appendLines.push(`\u{1F4CE} ${((_b = item.file_item) == null ? void 0 : _b.file_name) || "\u6587\u4EF6"}`);
            }
            break;
          case 5:
            if (mediaPath) {
              appendLines.push(`\u{1F3AC} [\u89C6\u9891](${mediaPath})`);
            } else {
              appendLines.push(`\u{1F3AC} \u89C6\u9891`);
            }
            break;
        }
      }
    }
    appendLines.push("");
    if (this.settings.enableFrontmatter) {
      const updatedFrontmatter = { ...frontmatter, wechat_last_sync: (/* @__PURE__ */ new Date()).toISOString() };
      const updatedContent = this.updateFrontmatterInContent(existing, updatedFrontmatter);
      await this.app.vault.modify(file, updatedContent + appendLines.join("\n"));
    } else {
      await this.app.vault.modify(file, existing + appendLines.join("\n"));
    }
  }
  extractSenderFromGroup(msg) {
    var _a;
    const text = this.extractText(msg);
    const atMatch = text.match(/^@([^\s:：]+)/);
    if (atMatch)
      return atMatch[1];
    return ((_a = msg.from_user_id) == null ? void 0 : _a.split("@")[0]) || "\u7FA4\u6210\u5458";
  }
  formatTime(createTimeMs) {
    const date = createTimeMs ? new Date(createTimeMs) : /* @__PURE__ */ new Date();
    return date.toLocaleTimeString("zh-CN", {
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit"
    });
  }
  updateFrontmatterInContent(content, frontmatter) {
    if (!content.startsWith("---"))
      return content;
    const endIndex = content.indexOf("---", 3);
    if (endIndex === -1)
      return content;
    const lines = ["---"];
    for (const [key, value] of Object.entries(frontmatter)) {
      if (value !== void 0 && value !== null) {
        lines.push(`${key}: ${typeof value === "string" ? `"${value}"` : value}`);
      }
    }
    lines.push("---");
    return lines.join("\n") + content.slice(endIndex + 3);
  }
};

// src/sync/noteExporter.ts
var import_obsidian4 = require("obsidian");
var path = __toESM(require("path"));
var NoteExporter = class {
  constructor(app, settings) {
    this.sender = null;
    this.app = app;
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  setSender(sender) {
    this.sender = sender;
  }
  async sendNoteToWechat(file, contextToken, toUserId) {
    if (!this.sender) {
      new import_obsidian4.Notice("\u5FAE\u4FE1\u53D1\u9001\u5668\u672A\u521D\u59CB\u5316");
      return false;
    }
    const content = await this.app.vault.read(file);
    const cleanContent = this.stripFrontmatter(content);
    if (!cleanContent.trim()) {
      new import_obsidian4.Notice("\u7B14\u8BB0\u5185\u5BB9\u4E3A\u7A7A\uFF0C\u65E0\u6CD5\u53D1\u9001");
      return false;
    }
    const truncated = this.truncateForWechat(cleanContent);
    const result = await this.sender.sendText(contextToken, truncated, toUserId);
    if (result.ret === 0) {
      new import_obsidian4.Notice(`\u5DF2\u53D1\u9001\u5230\u5FAE\u4FE1: ${file.basename}`);
      return true;
    } else {
      new import_obsidian4.Notice(`\u53D1\u9001\u5931\u8D25: ${result.errmsg || "\u672A\u77E5\u9519\u8BEF"}`);
      return false;
    }
  }
  async sendNoteToLatestContext(file) {
    if (!this.sender) {
      new import_obsidian4.Notice("\u5FAE\u4FE1\u53D1\u9001\u5668\u672A\u521D\u59CB\u5316");
      return false;
    }
    const cache = this.app.metadataCache.getFileCache(file);
    const frontmatter = cache == null ? void 0 : cache.frontmatter;
    const contextToken = frontmatter == null ? void 0 : frontmatter.wechat_context_token;
    if (contextToken) {
      return this.sendNoteToWechat(file, contextToken);
    }
    new import_obsidian4.Notice("\u8BE5\u7B14\u8BB0\u6CA1\u6709\u5173\u8054\u7684\u5FAE\u4FE1\u4F1A\u8BDD\uFF0C\u8BF7\u5148\u6536\u5230\u5FAE\u4FE1\u6D88\u606F\u540E\u518D\u56DE\u590D");
    return false;
  }
  async sendCurrentNoteToWechat(contextToken) {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile || activeFile.extension !== "md") {
      new import_obsidian4.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u6587\u4EF6");
      return false;
    }
    return this.sendNoteToWechat(activeFile, contextToken);
  }
  async sendTextReply(contextToken, text, toUserId) {
    if (!this.sender) {
      new import_obsidian4.Notice("\u5FAE\u4FE1\u53D1\u9001\u5668\u672A\u521D\u59CB\u5316");
      return false;
    }
    const result = await this.sender.sendText(contextToken, text, toUserId);
    if (result.ret === 0) {
      new import_obsidian4.Notice("\u6D88\u606F\u5DF2\u53D1\u9001\u5230\u5FAE\u4FE1");
      return true;
    } else {
      new import_obsidian4.Notice(`\u53D1\u9001\u5931\u8D25: ${result.errmsg || "\u672A\u77E5\u9519\u8BEF"}`);
      return false;
    }
  }
  async sendImageToWechat(contextToken, imagePath) {
    if (!this.sender) {
      new import_obsidian4.Notice("\u5FAE\u4FE1\u53D1\u9001\u5668\u672A\u521D\u59CB\u5316");
      return false;
    }
    try {
      const adapter = this.app.vault.adapter;
      if (!("readBinary" in adapter)) {
        new import_obsidian4.Notice("\u4EC5\u652F\u6301\u684C\u9762\u7AEF\u53D1\u9001\u56FE\u7247");
        return false;
      }
      const imageBuffer = await adapter.readBinary(imagePath);
      const buffer = Buffer.from(imageBuffer);
      const md5 = ILinkCrypto.calculateMD5(buffer);
      const aesKey = ILinkCrypto.generateAESKey();
      const fileSize = buffer.length;
      const result = await this.sender.sendImage(
        contextToken,
        "",
        aesKey,
        md5,
        fileSize,
        0,
        0
      );
      if (result.ret === 0) {
        new import_obsidian4.Notice("\u56FE\u7247\u5DF2\u53D1\u9001\u5230\u5FAE\u4FE1");
        return true;
      } else {
        new import_obsidian4.Notice(`\u56FE\u7247\u53D1\u9001\u5931\u8D25: ${result.errmsg || "\u672A\u77E5\u9519\u8BEF"}`);
        return false;
      }
    } catch (e) {
      new import_obsidian4.Notice(`\u56FE\u7247\u53D1\u9001\u5931\u8D25: ${e instanceof Error ? e.message : String(e)}`);
      return false;
    }
  }
  async sendFileToWechat(contextToken, filePath2) {
    if (!this.sender) {
      new import_obsidian4.Notice("\u5FAE\u4FE1\u53D1\u9001\u5668\u672A\u521D\u59CB\u5316");
      return false;
    }
    try {
      const adapter = this.app.vault.adapter;
      if (!("readBinary" in adapter)) {
        new import_obsidian4.Notice("\u4EC5\u652F\u6301\u684C\u9762\u7AEF\u53D1\u9001\u6587\u4EF6");
        return false;
      }
      const fileBuffer = await adapter.readBinary(filePath2);
      const buffer = Buffer.from(fileBuffer);
      const md5 = ILinkCrypto.calculateMD5(buffer);
      const aesKey = ILinkCrypto.generateAESKey();
      const fileSize = buffer.length;
      const fileName = path.basename(filePath2);
      const result = await this.sender.sendFile(
        contextToken,
        "",
        aesKey,
        md5,
        fileSize,
        fileName
      );
      if (result.ret === 0) {
        new import_obsidian4.Notice("\u6587\u4EF6\u5DF2\u53D1\u9001\u5230\u5FAE\u4FE1");
        return true;
      } else {
        new import_obsidian4.Notice(`\u6587\u4EF6\u53D1\u9001\u5931\u8D25: ${result.errmsg || "\u672A\u77E5\u9519\u8BEF"}`);
        return false;
      }
    } catch (e) {
      new import_obsidian4.Notice(`\u6587\u4EF6\u53D1\u9001\u5931\u8D25: ${e instanceof Error ? e.message : String(e)}`);
      return false;
    }
  }
  stripFrontmatter(content) {
    if (!content.startsWith("---"))
      return content;
    const endIndex = content.indexOf("---", 3);
    if (endIndex === -1)
      return content;
    return content.slice(endIndex + 3).trim();
  }
  truncateForWechat(text, maxLength = 4096) {
    if (text.length <= maxLength)
      return text;
    return text.slice(0, maxLength - 3) + "...";
  }
};

// src/sync/conflictResolver.ts
var import_obsidian5 = require("obsidian");
var ConflictResolver = class {
  constructor(app, settings) {
    this.app = app;
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  async resolve(filePath2, localContent, remoteContent, localMtime, remoteMtime) {
    switch (this.settings.conflictStrategy) {
      case "wechat_first":
        return remoteContent;
      case "local_first":
        return localContent;
      case "create_conflict":
        return this.createConflictCopy(filePath2, localContent, remoteContent, localMtime, remoteMtime);
      default:
        return this.createConflictCopy(filePath2, localContent, remoteContent, localMtime, remoteMtime);
    }
  }
  detectConflict(localContent, remoteContent, localMtime, remoteMtime, lastSync) {
    const localModified = localMtime > lastSync;
    const remoteModified = remoteMtime > lastSync;
    if (localModified && remoteModified) {
      if (localContent !== remoteContent) {
        return {
          localContent,
          remoteContent,
          localMtime,
          remoteMtime,
          filePath
        };
      }
    }
    if (localModified && !remoteModified) {
      return null;
    }
    if (remoteModified && !localModified) {
      return null;
    }
    if (localContent !== remoteContent) {
      return {
        localContent,
        remoteContent,
        localMtime,
        remoteMtime,
        filePath
      };
    }
    return null;
  }
  async createConflictCopy(filePath2, localContent, remoteContent, localMtime, remoteMtime) {
    const conflictPath = this.getConflictFilePath(filePath2, remoteMtime);
    const file = this.app.vault.getAbstractFileByPath(filePath2);
    if (file instanceof import_obsidian5.TFile) {
      const conflictContent = this.buildConflictContent(
        localContent,
        remoteContent,
        localMtime,
        remoteMtime
      );
      await this.app.vault.create(conflictPath, conflictContent);
      new import_obsidian5.Notice(`\u51B2\u7A81\u5DF2\u521B\u5EFA\u526F\u672C: ${conflictPath}`);
    }
    return remoteContent;
  }
  getConflictFilePath(originalPath, mtime) {
    const ext = originalPath.lastIndexOf(".");
    const base = ext >= 0 ? originalPath.slice(0, ext) : originalPath;
    const extStr = ext >= 0 ? originalPath.slice(ext) : "";
    const dateStr = new Date(mtime).toISOString().replace(/[:.]/g, "-");
    return `${base}-conflict-${dateStr}${extStr}`;
  }
  buildConflictContent(localContent, remoteContent, localMtime, remoteMtime) {
    const lines = [];
    lines.push("---");
    lines.push("wechat_conflict: true");
    lines.push(`local_modified: "${new Date(localMtime).toISOString()}"`);
    lines.push(`remote_modified: "${new Date(remoteMtime).toISOString()}"`);
    lines.push("---");
    lines.push("");
    lines.push("## \u26A0\uFE0F \u51B2\u7A81\u5185\u5BB9");
    lines.push("");
    lines.push("### \u672C\u5730\u7248\u672C");
    lines.push("```");
    lines.push(localContent);
    lines.push("```");
    lines.push("");
    lines.push("### \u5FAE\u4FE1\u7248\u672C");
    lines.push("```");
    lines.push(remoteContent);
    lines.push("```");
    return lines.join("\n");
  }
};

// src/sync/syncEngine.ts
var import_obsidian6 = require("obsidian");
var fs = __toESM(require("fs"));
var path2 = __toESM(require("path"));
var os = __toESM(require("os"));
var SyncEngine = class {
  constructor(app, settings) {
    this.progressCallback = null;
    this.app = app;
    this.settings = settings;
    this.conflictResolver = new ConflictResolver(app, settings);
    this.state = { version: 1, lastFullSync: 0, files: {} };
    this.vaultPath = this.getVaultPath();
  }
  updateSettings(settings) {
    this.settings = settings;
    this.conflictResolver.updateSettings(settings);
  }
  setProgressCallback(cb) {
    this.progressCallback = cb;
  }
  loadState() {
    const stateFile = path2.join(this.vaultPath, ".obsidian", ".wechat-sync-state.json");
    try {
      if (fs.existsSync(stateFile)) {
        const data = JSON.parse(fs.readFileSync(stateFile, "utf-8"));
        this.state = data;
      }
    } catch (e) {
    }
  }
  saveState() {
    const stateFile = path2.join(this.vaultPath, ".obsidian", ".wechat-sync-state.json");
    try {
      fs.writeFileSync(stateFile, JSON.stringify(this.state, null, 2), "utf-8");
    } catch (e) {
    }
  }
  async syncAll() {
    const progress = {
      total: 0,
      current: 0,
      currentFile: "",
      phase: "scanning",
      errors: []
    };
    this.emitProgress(progress);
    const syncFolder = (0, import_obsidian6.normalizePath)(this.settings.syncFolder);
    const files = this.app.vault.getMarkdownFiles().filter(
      (f) => f.path.startsWith(syncFolder)
    );
    progress.total = files.length;
    progress.phase = "syncing";
    this.emitProgress(progress);
    for (const file of files) {
      progress.currentFile = file.path;
      this.emitProgress(progress);
      try {
        await this.syncSingleFile(file);
      } catch (e) {
        progress.errors.push({
          file: file.path,
          message: e instanceof Error ? e.message : String(e)
        });
      }
      progress.current++;
      this.emitProgress(progress);
    }
    progress.phase = progress.errors.length > 0 ? "error" : "done";
    this.emitProgress(progress);
    this.state.lastFullSync = Date.now();
    this.saveState();
    return progress;
  }
  async syncSingleFile(file) {
    const cache = this.app.metadataCache.getFileCache(file);
    const frontmatter = cache == null ? void 0 : cache.frontmatter;
    if (!(frontmatter == null ? void 0 : frontmatter.wechat_msg_id) && !(frontmatter == null ? void 0 : frontmatter.wechat_session))
      return;
    const content = await this.app.vault.read(file);
    const stat = await this.app.vault.adapter.stat(file.path);
    const localMtime = (stat == null ? void 0 : stat.mtime) || 0;
    const stateKey = file.path;
    const existingState = this.state.files[stateKey];
    if (existingState) {
      const conflict = this.conflictResolver.detectConflict(
        content,
        content,
        localMtime,
        existingState.remoteMtime,
        existingState.lastSync
      );
      if (conflict) {
        const resolved = await this.conflictResolver.resolve(
          file.path,
          conflict.localContent,
          conflict.remoteContent,
          conflict.localMtime,
          conflict.remoteMtime
        );
        if (resolved !== content) {
          await this.app.vault.modify(file, resolved);
        }
      }
    }
    this.state.files[stateKey] = {
      localPath: file.path,
      msgId: (frontmatter == null ? void 0 : frontmatter.wechat_msg_id) || 0,
      sessionId: (frontmatter == null ? void 0 : frontmatter.wechat_session) || "",
      localMtime,
      remoteMtime: (existingState == null ? void 0 : existingState.remoteMtime) || localMtime,
      lastSync: Date.now(),
      syncVersion: (frontmatter == null ? void 0 : frontmatter.wechat_sync_version) || 1,
      contextToken: frontmatter == null ? void 0 : frontmatter.wechat_context_token
    };
    this.saveState();
  }
  async pushLocalChanges() {
    const progress = {
      total: 0,
      current: 0,
      currentFile: "",
      phase: "scanning",
      errors: []
    };
    this.emitProgress(progress);
    const syncFolder = (0, import_obsidian6.normalizePath)(this.settings.syncFolder);
    const files = this.app.vault.getMarkdownFiles().filter((f) => {
      if (!f.path.startsWith(syncFolder))
        return false;
      const state = this.state.files[f.path];
      if (!state)
        return false;
      const stat = this.app.vault.adapter.stat(f.path);
      return stat && stat.mtime > state.lastSync;
    });
    progress.total = files.length;
    progress.phase = "syncing";
    this.emitProgress(progress);
    for (const file of files) {
      progress.currentFile = file.path;
      this.emitProgress(progress);
      try {
        await this.syncSingleFile(file);
      } catch (e) {
        progress.errors.push({
          file: file.path,
          message: e instanceof Error ? e.message : String(e)
        });
      }
      progress.current++;
      this.emitProgress(progress);
    }
    progress.phase = progress.errors.length > 0 ? "error" : "done";
    this.emitProgress(progress);
    return progress;
  }
  async pullRemoteChanges() {
    return this.syncAll();
  }
  getFileState(filePath2) {
    return this.state.files[filePath2] || null;
  }
  updateFileRemoteMtime(filePath2, remoteMtime) {
    if (this.state.files[filePath2]) {
      this.state.files[filePath2].remoteMtime = remoteMtime;
    }
    this.saveState();
  }
  emitProgress(progress) {
    if (this.progressCallback) {
      this.progressCallback({ ...progress });
    }
  }
  getVaultPath() {
    const adapter = this.app.vault.adapter;
    if (adapter instanceof import_obsidian6.FileSystemAdapter) {
      return adapter.getBasePath();
    }
    return os.homedir();
  }
};

// src/ui/index.ts
init_qrCodeModal();

// src/ui/syncModal.ts
var import_obsidian7 = require("obsidian");
var SyncModal = class extends import_obsidian7.Modal {
  constructor(app, progress) {
    super(app);
    this.progressEl = null;
    this.detailsEl = null;
    this.progress = progress;
  }
  updateProgress(progress) {
    this.progress = progress;
    this.render();
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("wechat-sync-modal");
    contentEl.createEl("h2", { text: "\u5FAE\u4FE1\u540C\u6B65" });
    this.progressEl = contentEl.createDiv({
      cls: "wechat-sync-progress"
    });
    this.detailsEl = contentEl.createDiv({
      cls: "wechat-sync-details"
    });
    this.render();
  }
  onClose() {
    this.contentEl.empty();
  }
  render() {
    this.renderProgress();
    this.renderDetails();
  }
  renderProgress() {
    if (!this.progressEl)
      return;
    this.progressEl.empty();
    const phaseMap = {
      idle: "\u7A7A\u95F2",
      scanning: "\u626B\u63CF\u4E2D...",
      syncing: `\u540C\u6B65\u4E2D (${this.progress.current}/${this.progress.total})`,
      done: "\u540C\u6B65\u5B8C\u6210",
      error: "\u540C\u6B65\u51FA\u9519"
    };
    this.progressEl.createEl("p", {
      text: phaseMap[this.progress.phase],
      cls: `wechat-sync-phase-${this.progress.phase}`
    });
    if (this.progress.total > 0) {
      const percent = Math.round(
        this.progress.current / this.progress.total * 100
      );
      const barContainer = this.progressEl.createDiv({
        cls: "wechat-sync-progress-bar-container"
      });
      const bar = barContainer.createDiv({
        cls: "wechat-sync-progress-bar"
      });
      bar.style.width = `${percent}%`;
      this.progressEl.createEl("span", {
        text: `${percent}%`,
        cls: "wechat-sync-progress-text"
      });
    }
    if (this.progress.currentFile) {
      this.progressEl.createEl("p", {
        text: `\u5F53\u524D: ${this.progress.currentFile}`,
        cls: "wechat-sync-current-file"
      });
    }
  }
  renderDetails() {
    if (!this.detailsEl)
      return;
    this.detailsEl.empty();
    if (this.progress.errors.length > 0) {
      this.detailsEl.createEl("h3", { text: "\u9519\u8BEF" });
      for (const err of this.progress.errors) {
        this.detailsEl.createEl("p", {
          text: `${err.file}: ${err.message}`,
          cls: "wechat-sync-error"
        });
      }
    }
  }
};

// src/ui/syncStatusBar.ts
var SyncStatusBar = class {
  constructor() {
    this.statusBarItem = null;
    this.status = "not_configured";
  }
  mount(element) {
    this.statusBarItem = element;
    this.statusBarItem.addClass("wechat-sync-status-bar");
    this.render();
  }
  setStatus(status) {
    this.status = status;
    this.render();
  }
  setIdle() {
    this.setStatus("authed");
  }
  setSyncing() {
    this.setStatus("polling");
  }
  setError(msg) {
    var _a;
    (_a = this.statusBarItem) == null ? void 0 : _a.setAttr("aria-label", msg);
    this.setStatus("error");
  }
  updateProgress(progress) {
    if (!this.statusBarItem)
      return;
    if (progress.total > 0) {
      this.statusBarItem.setText(
        `\u5FAE\u4FE1\u540C\u6B65: ${progress.current}/${progress.total}`
      );
    }
  }
  render() {
    if (!this.statusBarItem)
      return;
    const statusConfig = {
      not_configured: {
        icon: "\u{1F50C}",
        text: "\u5FAE\u4FE1: \u672A\u914D\u7F6E",
        cls: "wechat-status-not-configured"
      },
      configured_not_authed: {
        icon: "\u{1F510}",
        text: "\u5FAE\u4FE1: \u672A\u767B\u5F55",
        cls: "wechat-status-not-authed"
      },
      authed: {
        icon: "\u2705",
        text: "\u5FAE\u4FE1: \u5DF2\u8FDE\u63A5",
        cls: "wechat-status-authed"
      },
      polling: {
        icon: "\u{1F504}",
        text: "\u5FAE\u4FE1: \u540C\u6B65\u4E2D",
        cls: "wechat-status-polling"
      },
      error: {
        icon: "\u274C",
        text: "\u5FAE\u4FE1: \u9519\u8BEF",
        cls: "wechat-status-error"
      }
    };
    const config = statusConfig[this.status];
    this.statusBarItem.setText(`${config.icon} ${config.text}`);
    this.statusBarItem.className = `wechat-sync-status-bar ${config.cls}`;
  }
};

// src/ui/wechatReplyModal.ts
var import_obsidian8 = require("obsidian");
var WeChatReplyModal = class extends import_obsidian8.Modal {
  constructor(app, contextTokens) {
    super(app);
    this.selectedEntry = null;
    this.replyText = "";
    this.onSend = null;
    this.textArea = null;
    this.contextTokens = contextTokens;
    if (contextTokens.length > 0) {
      this.selectedEntry = contextTokens[0];
    }
  }
  setOnSend(callback) {
    this.onSend = callback;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("wechat-sync-reply-modal");
    contentEl.createEl("h2", { text: "\u56DE\u590D\u5FAE\u4FE1\u6D88\u606F" });
    if (this.contextTokens.length === 0) {
      contentEl.createEl("p", {
        text: "\u6682\u65E0\u53EF\u7528\u7684\u5FAE\u4FE1\u4F1A\u8BDD\u3002\u8BF7\u5148\u6536\u5230\u5FAE\u4FE1\u6D88\u606F\u540E\u518D\u56DE\u590D\u3002",
        cls: "wechat-sync-no-sessions"
      });
      return;
    }
    new import_obsidian8.Setting(contentEl).setName("\u9009\u62E9\u4F1A\u8BDD").setDesc("\u9009\u62E9\u8981\u56DE\u590D\u7684\u5FAE\u4FE1\u4F1A\u8BDD").addDropdown((dropdown) => {
      for (const entry of this.contextTokens) {
        const label = entry.lastMessage ? `${entry.fromUserId.slice(0, 12)}... - "${entry.lastMessage.slice(0, 30)}"` : entry.fromUserId;
        dropdown.addOption(entry.contextToken, label);
      }
      if (this.selectedEntry) {
        dropdown.setValue(this.selectedEntry.contextToken);
      }
      dropdown.onChange((value) => {
        this.selectedEntry = this.contextTokens.find((e) => e.contextToken === value) || null;
      });
    });
    contentEl.createEl("p", {
      text: "\u56DE\u590D\u5185\u5BB9:",
      cls: "wechat-sync-reply-label"
    });
    this.textArea = new import_obsidian8.TextAreaComponent(contentEl);
    this.textArea.setPlaceholder("\u8F93\u5165\u8981\u53D1\u9001\u5230\u5FAE\u4FE1\u7684\u6D88\u606F...").setValue(this.replyText).onChange((value) => {
      this.replyText = value;
    });
    this.textArea.inputEl.addClass("wechat-sync-reply-textarea");
    this.textArea.inputEl.rows = 6;
    const buttonContainer = contentEl.createDiv({
      cls: "wechat-sync-reply-buttons"
    });
    const sendBtn = buttonContainer.createEl("button", {
      text: "\u53D1\u9001",
      cls: "mod-cta"
    });
    sendBtn.addEventListener("click", async () => {
      await this.handleSend();
    });
    const cancelBtn = buttonContainer.createEl("button", {
      text: "\u53D6\u6D88"
    });
    cancelBtn.addEventListener("click", () => {
      this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
  async handleSend() {
    if (!this.replyText.trim())
      return;
    if (!this.selectedEntry)
      return;
    if (!this.onSend)
      return;
    try {
      await this.onSend(
        this.selectedEntry.contextToken,
        this.replyText,
        this.selectedEntry.fromUserId
      );
      this.close();
    } catch (e) {
      console.error("[WeChat Sync] \u53D1\u9001\u5931\u8D25:", e);
    }
  }
};

// src/ui/wechatChatView.ts
var import_obsidian9 = require("obsidian");
var WECHAT_CHAT_VIEW_TYPE = "wechat-sync-chat";
var WeChatChatView = class extends import_obsidian9.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.messages = [];
    this.messagesContainer = null;
    this.inputEl = null;
    this.statusEl = null;
    this.toggleBtn = null;
    this.statusUnregister = null;
    this.plugin = plugin;
  }
  getViewType() {
    return WECHAT_CHAT_VIEW_TYPE;
  }
  getDisplayText() {
    return "\u5FAE\u4FE1\u804A\u5929";
  }
  getIcon() {
    return "message-circle";
  }
  onOpen() {
    var _a;
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("wechat-chat-container");
    const header = container.createDiv({ cls: "wechat-chat-header" });
    header.createEl("span", { text: "\u5FAE\u4FE1\u804A\u5929", cls: "wechat-chat-title" });
    this.statusEl = header.createSpan({ cls: "wechat-chat-status" });
    this.updateStatus();
    this.messagesContainer = container.createDiv({ cls: "wechat-chat-messages" });
    const inputContainer = container.createDiv({ cls: "wechat-chat-input-container" });
    this.inputEl = inputContainer.createEl("textarea", {
      cls: "wechat-chat-input",
      attr: {
        placeholder: "\u8F93\u5165\u6D88\u606F\uFF0C\u6309 Enter \u53D1\u9001\uFF0CShift+Enter \u6362\u884C...",
        rows: "3"
      }
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendCurrentMessage();
      }
    });
    const buttonRow = inputContainer.createDiv({ cls: "wechat-chat-button-row" });
    const sendBtn = buttonRow.createEl("button", {
      text: "\u53D1\u9001",
      cls: "mod-cta wechat-chat-send-btn"
    });
    sendBtn.addEventListener("click", () => this.sendCurrentMessage());
    const loginBtn = buttonRow.createEl("button", {
      text: this.plugin.ilinkAuth.isAuthenticated ? "\u91CD\u65B0\u767B\u5F55" : "\u626B\u7801\u767B\u5F55",
      cls: "wechat-chat-login-btn"
    });
    loginBtn.addEventListener("click", () => {
      this.plugin.showQRLogin();
    });
    this.toggleBtn = buttonRow.createEl("button", {
      text: ((_a = this.plugin.poller) == null ? void 0 : _a.isRunning) ? "\u505C\u6B62\u76D1\u542C" : "\u5F00\u59CB\u76D1\u542C",
      cls: "wechat-chat-toggle-btn"
    });
    this.toggleBtn.addEventListener("click", async () => {
      var _a2;
      if ((_a2 = this.plugin.poller) == null ? void 0 : _a2.isRunning) {
        this.plugin.stopPoller();
      } else {
        await this.plugin.startPoller();
      }
      this.updateStatus();
      this.updateToggleButton();
    });
    this.showWelcomeGuide();
    this.registerEvent(
      this.plugin.app.workspace.on("we-chat-sync:status", (status) => {
        this.onPollerStatusChange(status);
      })
    );
  }
  onClose() {
    this.messagesContainer = null;
    this.inputEl = null;
    this.statusEl = null;
    this.toggleBtn = null;
    if (this.statusUnregister) {
      this.statusUnregister();
      this.statusUnregister = null;
    }
  }
  onPollerStatusChange(status) {
    this.updateStatus();
    this.updateToggleButton();
    if (status === "connected") {
      this.addSystemMessage("\u2705 \u8FDE\u63A5\u6210\u529F\uFF01\u6B63\u5728\u76D1\u542C\u5FAE\u4FE1\u6D88\u606F...");
    } else if (status === "session_expired") {
      this.addSystemMessage("\u26A0\uFE0F \u5FAE\u4FE1\u4F1A\u8BDD\u5DF2\u8FC7\u671F\uFF0C\u8BF7\u91CD\u65B0\u626B\u7801\u767B\u5F55");
    } else if (status === "reconnecting") {
      this.addSystemMessage("\u{1F504} \u8FDE\u63A5\u4E2D\u65AD\uFF0C\u6B63\u5728\u91CD\u8FDE...");
    } else if (status === "stopped") {
      this.addSystemMessage("\u23F9 \u5DF2\u505C\u6B62\u76D1\u542C");
    }
  }
  updateStatus() {
    var _a;
    if (!this.statusEl)
      return;
    const isPolling = (_a = this.plugin.poller) == null ? void 0 : _a.isRunning;
    const isAuthed = this.plugin.ilinkAuth.isAuthenticated;
    if (isPolling) {
      this.statusEl.setText("\u25CF \u76D1\u542C\u4E2D");
      this.statusEl.className = "wechat-chat-status wechat-status-online";
    } else if (isAuthed) {
      this.statusEl.setText("\u25CB \u5DF2\u767B\u5F55");
      this.statusEl.className = "wechat-chat-status wechat-status-idle";
    } else {
      this.statusEl.setText("\u25CB \u672A\u767B\u5F55");
      this.statusEl.className = "wechat-chat-status wechat-status-offline";
    }
  }
  updateToggleButton() {
    var _a;
    if (!this.toggleBtn)
      return;
    this.toggleBtn.setText(((_a = this.plugin.poller) == null ? void 0 : _a.isRunning) ? "\u505C\u6B62\u76D1\u542C" : "\u5F00\u59CB\u76D1\u542C");
  }
  showWelcomeGuide() {
    var _a;
    const isAuthed = this.plugin.ilinkAuth.isAuthenticated;
    const isPolling = (_a = this.plugin.poller) == null ? void 0 : _a.isRunning;
    if (!isAuthed) {
      this.addSystemMessage("\u{1F44B} \u6B22\u8FCE\u4F7F\u7528\u5FAE\u4FE1\u804A\u5929\uFF01");
      this.addSystemMessage("\u{1F4CC} \u4F7F\u7528\u6B65\u9AA4\uFF1A");
      this.addSystemMessage("1. \u70B9\u51FB\u4E0B\u65B9\u300C\u626B\u7801\u767B\u5F55\u300D\u6309\u94AE");
      this.addSystemMessage("2. \u7528\u624B\u673A\u5FAE\u4FE1\u626B\u63CF\u5F39\u51FA\u7684\u4E8C\u7EF4\u7801");
      this.addSystemMessage("3. \u767B\u5F55\u6210\u529F\u540E\u70B9\u51FB\u300C\u5F00\u59CB\u76D1\u542C\u300D");
      this.addSystemMessage("4. \u5728\u5FAE\u4FE1\u4E2D\u7ED9 ClawBot \u53D1\u6D88\u606F\uFF0C\u8FD9\u91CC\u5C31\u80FD\u6536\u5230");
      this.addSystemMessage("5. \u6536\u5230\u6D88\u606F\u540E\uFF0C\u53EF\u4EE5\u5728\u8FD9\u91CC\u76F4\u63A5\u56DE\u590D");
    } else if (!isPolling) {
      this.addSystemMessage("\u2705 \u5DF2\u767B\u5F55\uFF0C\u70B9\u51FB\u300C\u5F00\u59CB\u76D1\u542C\u300D\u63A5\u6536\u6D88\u606F");
    } else {
      this.addSystemMessage("\u2705 \u6B63\u5728\u76D1\u542C\u5FAE\u4FE1\u6D88\u606F...");
      this.addSystemMessage("\u{1F4A1} \u8BF7\u5728\u5FAE\u4FE1\u4E2D\u7ED9 ClawBot \u53D1\u6D88\u606F\uFF0C\u6D88\u606F\u4F1A\u663E\u793A\u5728\u8FD9\u91CC");
    }
  }
  addMessage(msg) {
    const text = this.extractText(msg);
    if (!text)
      return;
    const isUser = msg.message_type === 1;
    const chatMsg = {
      sender: isUser ? "user" : "bot",
      text,
      time: msg.create_time_ms ? new Date(msg.create_time_ms).toLocaleTimeString("zh-CN", {
        hour: "2-digit",
        minute: "2-digit"
      }) : (/* @__PURE__ */ new Date()).toLocaleTimeString("zh-CN", {
        hour: "2-digit",
        minute: "2-digit"
      }),
      contextToken: msg.context_token,
      fromUserId: msg.from_user_id
    };
    this.messages.push(chatMsg);
    this.renderMessage(chatMsg);
    this.scrollToBottom();
  }
  addSystemMessage(text) {
    const msg = { sender: "system", text, time: "" };
    this.messages.push(msg);
    this.renderMessage(msg);
  }
  extractText(msg) {
    if (!msg.item_list)
      return "";
    return msg.item_list.filter((item) => item.type === 1 && item.text_item).map((item) => item.text_item.text).join("\n");
  }
  async sendCurrentMessage() {
    if (!this.inputEl)
      return;
    const text = this.inputEl.value.trim();
    if (!text)
      return;
    if (!this.plugin.ilinkAuth.isAuthenticated) {
      new import_obsidian9.Notice("\u8BF7\u5148\u626B\u7801\u767B\u5F55\u5FAE\u4FE1");
      return;
    }
    const contextEntry = this.getLatestContextToken();
    if (!contextEntry) {
      this.addSystemMessage("\u26A0\uFE0F \u6682\u65E0\u53EF\u7528\u7684\u5FAE\u4FE1\u4F1A\u8BDD");
      this.addSystemMessage("\u{1F4A1} \u8BF7\u5148\u5728\u5FAE\u4FE1\u4E2D\u7ED9 ClawBot \u53D1\u4E00\u6761\u6D88\u606F\uFF0C\u6536\u5230\u6D88\u606F\u540E\u5C31\u53EF\u4EE5\u56DE\u590D\u4E86");
      new import_obsidian9.Notice("\u8BF7\u5148\u5728\u5FAE\u4FE1\u4E2D\u7ED9 ClawBot \u53D1\u4E00\u6761\u6D88\u606F");
      return;
    }
    this.inputEl.value = "";
    const chatMsg = {
      sender: "bot",
      text,
      time: (/* @__PURE__ */ new Date()).toLocaleTimeString("zh-CN", {
        hour: "2-digit",
        minute: "2-digit"
      })
    };
    this.messages.push(chatMsg);
    this.renderMessage(chatMsg);
    this.scrollToBottom();
    if (this.plugin.noteExporter) {
      const success = await this.plugin.noteExporter.sendTextReply(
        contextEntry.contextToken,
        text,
        contextEntry.fromUserId
      );
      if (!success) {
        this.addSystemMessage("\u274C \u6D88\u606F\u53D1\u9001\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5\u7F51\u7EDC\u8FDE\u63A5");
      } else {
        this.addSystemMessage("\u2705 \u6D88\u606F\u5DF2\u53D1\u9001");
      }
    }
  }
  getLatestContextToken() {
    const handler = this.plugin.messageHandler;
    if (!(handler == null ? void 0 : handler.contextTokens))
      return null;
    const tokens = Array.from(handler.contextTokens.values());
    if (tokens.length === 0)
      return null;
    return tokens.reduce((a, b) => a.timestamp > b.timestamp ? a : b);
  }
  renderMessage(msg) {
    if (!this.messagesContainer)
      return;
    const msgEl = this.messagesContainer.createDiv({
      cls: `wechat-chat-msg wechat-chat-msg-${msg.sender}`
    });
    if (msg.sender === "system") {
      msgEl.createEl("div", {
        text: msg.text,
        cls: "wechat-chat-system-text"
      });
      return;
    }
    const headerEl = msgEl.createDiv({ cls: "wechat-chat-msg-header" });
    headerEl.createSpan({
      text: msg.sender === "user" ? `\u5BF9\u65B9` : "\u6211",
      cls: "wechat-chat-msg-sender"
    });
    headerEl.createSpan({
      text: msg.time,
      cls: "wechat-chat-msg-time"
    });
    msgEl.createEl("div", {
      text: msg.text,
      cls: "wechat-chat-msg-text"
    });
  }
  scrollToBottom() {
    if (this.messagesContainer) {
      this.messagesContainer.scrollTop = this.messagesContainer.scrollHeight;
    }
  }
};

// src/updater.ts
var import_obsidian10 = require("obsidian");
var fs2 = __toESM(require("fs"));
var path3 = __toESM(require("path"));
var GITEE_OWNER = "hongjian_Ai";
var GITEE_REPO = "obsidian-wechat-sync";
var RELEASES_API = `https://gitee.com/api/v5/repos/${GITEE_OWNER}/${GITEE_REPO}/releases`;
function semverCompare(a, b) {
  const pa = a.replace(/^v/, "").split(/[\.\-]/);
  const pb = b.replace(/^v/, "").split(/[\.\-]/);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const na = parseInt(pa[i] || "0", 10);
    const nb = parseInt(pb[i] || "0", 10);
    if (na > nb)
      return 1;
    if (na < nb)
      return -1;
  }
  return 0;
}
async function checkForUpdate(currentVersion, accessToken) {
  try {
    let url = `${RELEASES_API}?direction=desc&per_page=10`;
    if (accessToken) {
      url += `&access_token=${encodeURIComponent(accessToken)}`;
    }
    const resp = await (0, import_obsidian10.requestUrl)({
      url,
      method: "GET"
    });
    const releases = resp.json;
    if (!releases || releases.length === 0)
      return null;
    const latest = releases.find((r) => !r.prerelease) || releases[0];
    const latestVersion = latest.tag_name.replace(/^v/, "");
    const hasUpdate = semverCompare(latestVersion, currentVersion) > 0;
    const assetUrls = {};
    for (const asset of latest.assets) {
      if (asset.name && asset.browser_download_url) {
        let dlUrl = asset.browser_download_url;
        if (accessToken && dlUrl.includes("gitee.com")) {
          const sep = dlUrl.includes("?") ? "&" : "?";
          dlUrl += `${sep}access_token=${encodeURIComponent(accessToken)}`;
        }
        assetUrls[asset.name] = dlUrl;
      }
    }
    return {
      hasUpdate,
      currentVersion,
      latestVersion,
      assetUrls,
      releaseNotes: latest.body || ""
    };
  } catch (e) {
    return null;
  }
}
async function performUpdate(pluginDir, assetUrls, onProgress) {
  const requiredFiles = ["main.js", "manifest.json"];
  const optionalFiles = ["styles.css"];
  try {
    for (const file of [...requiredFiles, ...optionalFiles]) {
      const url = assetUrls[file];
      if (!url) {
        if (requiredFiles.includes(file)) {
          throw new Error(`\u627E\u4E0D\u5230 ${file} \u7684\u4E0B\u8F7D\u94FE\u63A5`);
        }
        continue;
      }
      onProgress == null ? void 0 : onProgress(`\u4E0B\u8F7D ${file}...`);
      const resp = await (0, import_obsidian10.requestUrl)({ url, method: "GET" });
      const filePath2 = path3.join(pluginDir, file);
      fs2.writeFileSync(filePath2, Buffer.from(resp.arrayBuffer));
    }
    onProgress == null ? void 0 : onProgress("\u66F4\u65B0\u5B8C\u6210\uFF0C\u8BF7\u91CD\u65B0\u52A0\u8F7D\u63D2\u4EF6");
    new import_obsidian10.Notice("\u2705 WeChat Sync \u5DF2\u66F4\u65B0\uFF0C\u8BF7\u91CD\u65B0\u52A0\u8F7D\u63D2\u4EF6");
    return true;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    onProgress == null ? void 0 : onProgress(`\u66F4\u65B0\u5931\u8D25: ${msg}`);
    new import_obsidian10.Notice("\u274C \u66F4\u65B0\u5931\u8D25: " + msg);
    return false;
  }
}

// src/main.ts
var WeChatSyncPlugin = class extends import_obsidian11.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.ilinkAuth = new ILinkAuth();
    this.poller = null;
    this.sender = null;
    this.messageHandler = null;
    this.noteExporter = null;
    this.syncEngine = null;
    this.conflictResolver = null;
    this.statusBar = new SyncStatusBar();
    this.chatView = null;
    this.updateInfo = null;
    this.autoSyncTimer = null;
    this.pollerRunning = false;
  }
  async onload() {
    await this.loadSettings();
    this.messageHandler = new MessageHandler(this.app, this.settings);
    this.noteExporter = new NoteExporter(this.app, this.settings);
    this.syncEngine = new SyncEngine(this.app, this.settings);
    this.conflictResolver = new ConflictResolver(this.app, this.settings);
    this.registerView(WECHAT_CHAT_VIEW_TYPE, (leaf) => {
      this.chatView = new WeChatChatView(leaf, this);
      return this.chatView;
    });
    this.addSettingTab(new WeChatSyncSettingTab(this.app, this));
    this.app.workspace.onLayoutReady(() => {
      var _a;
      this.initStatusBar();
      this.initAutoSync();
      this.restoreAuth();
      (_a = this.syncEngine) == null ? void 0 : _a.loadState();
      this.checkUpdateOnStartup();
    });
    this.addRibbonIcon("message-circle", "WeChat Sync", async () => {
      await this.openChatView();
    });
    this.addCommand({
      id: "wechat-sync-open-chat",
      name: "\u6253\u5F00\u5FAE\u4FE1\u804A\u5929",
      callback: () => this.openChatView()
    });
    this.addCommand({
      id: "wechat-sync-start",
      name: "\u5F00\u59CB\u76D1\u542C\u5FAE\u4FE1\u6D88\u606F",
      callback: () => this.startPoller()
    });
    this.addCommand({
      id: "wechat-sync-stop",
      name: "\u505C\u6B62\u76D1\u542C\u5FAE\u4FE1\u6D88\u606F",
      callback: () => this.stopPoller()
    });
    this.addCommand({
      id: "wechat-sync-reply",
      name: "\u56DE\u590D\u5FAE\u4FE1\u6D88\u606F",
      callback: () => this.showReplyModal()
    });
    this.addCommand({
      id: "wechat-sync-send-current",
      name: "\u53D1\u9001\u5F53\u524D\u7B14\u8BB0\u5230\u5FAE\u4FE1",
      callback: () => this.sendCurrentNote()
    });
    this.addCommand({
      id: "wechat-sync-send-current-reply",
      name: "\u7528\u5F53\u524D\u7B14\u8BB0\u56DE\u590D\u5FAE\u4FE1",
      callback: () => this.sendCurrentNoteReply()
    });
    this.addCommand({
      id: "wechat-sync-login",
      name: "\u5FAE\u4FE1\u626B\u7801\u767B\u5F55",
      callback: () => this.showQRLogin()
    });
    this.addCommand({
      id: "wechat-sync-check-update",
      name: "\u68C0\u67E5\u66F4\u65B0",
      callback: () => this.manualCheckUpdate()
    });
    this.addCommand({
      id: "wechat-sync-sync-all",
      name: "\u540C\u6B65\u6240\u6709\u5FAE\u4FE1\u7B14\u8BB0",
      callback: () => this.syncAll()
    });
    this.addCommand({
      id: "wechat-sync-push",
      name: "\u63A8\u9001\u672C\u5730\u4FEE\u6539\u5230\u5FAE\u4FE1",
      callback: () => this.pushLocalChanges()
    });
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian11.TFile && file.extension === "md") {
          this.onFileModified(file);
        }
      })
    );
  }
  onunload() {
    this.stopPoller();
    this.stopAutoSync();
    this.app.workspace.detachLeavesOfType(WECHAT_CHAT_VIEW_TYPE);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    var _a, _b, _c, _d;
    await this.saveData(this.settings);
    (_a = this.messageHandler) == null ? void 0 : _a.updateSettings(this.settings);
    (_b = this.noteExporter) == null ? void 0 : _b.updateSettings(this.settings);
    (_c = this.syncEngine) == null ? void 0 : _c.updateSettings(this.settings);
    (_d = this.conflictResolver) == null ? void 0 : _d.updateSettings(this.settings);
  }
  async openChatView() {
    const existing = this.app.workspace.getLeavesOfType(WECHAT_CHAT_VIEW_TYPE);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const rightLeaf = this.app.workspace.getRightLeaf(false);
    if (rightLeaf) {
      await rightLeaf.setViewState({
        type: WECHAT_CHAT_VIEW_TYPE,
        active: true
      });
      this.app.workspace.revealLeaf(rightLeaf);
    }
  }
  async saveAuthData(data) {
    const authFilePath = path4.join(
      this.getVaultPath(),
      ".obsidian",
      ".wechat-sync-auth.json"
    );
    if (data) {
      const fs3 = require("fs");
      fs3.writeFileSync(authFilePath, JSON.stringify(data, null, 2), "utf-8");
    } else {
      try {
        const fs3 = require("fs");
        if (fs3.existsSync(authFilePath)) {
          fs3.unlinkSync(authFilePath);
        }
      } catch (e) {
      }
    }
  }
  async loadAuthData() {
    const authFilePath = path4.join(
      this.getVaultPath(),
      ".obsidian",
      ".wechat-sync-auth.json"
    );
    try {
      const fs3 = require("fs");
      if (fs3.existsSync(authFilePath)) {
        const data = JSON.parse(fs3.readFileSync(authFilePath, "utf-8"));
        return data;
      }
    } catch (e) {
    }
    return null;
  }
  async restoreAuth() {
    var _a;
    const savedAuth = await this.loadAuthData();
    if (savedAuth) {
      this.ilinkAuth.loadFromSaved(savedAuth);
      this.sender = new ILinkSender(savedAuth.token, savedAuth.baseUrl);
      (_a = this.noteExporter) == null ? void 0 : _a.setSender(this.sender);
      this.statusBar.setStatus("authed");
      if (this.settings.autoSync) {
        await this.startPoller();
      }
    }
  }
  async checkUpdateOnStartup() {
    if (!this.settings.checkUpdateOnStartup)
      return;
    try {
      const info = await checkForUpdate(this.manifest.version, this.settings.giteeAccessToken);
      if (info && info.hasUpdate) {
        this.updateInfo = info;
        new import_obsidian11.Notice(`WeChat Sync \u6709\u65B0\u7248\u672C ${info.latestVersion}\uFF0C\u8BF7\u5728\u8BBE\u7F6E\u4E2D\u66F4\u65B0`);
      }
    } catch (e) {
    }
  }
  async manualCheckUpdate() {
    const info = await checkForUpdate(this.manifest.version, this.settings.giteeAccessToken);
    if (!info) {
      new import_obsidian11.Notice("\u68C0\u67E5\u66F4\u65B0\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5\u7F51\u7EDC\u8FDE\u63A5");
      return null;
    }
    this.updateInfo = info;
    if (info.hasUpdate) {
      new import_obsidian11.Notice(`\u53D1\u73B0\u65B0\u7248\u672C ${info.latestVersion}\uFF08\u5F53\u524D ${info.currentVersion}\uFF09`);
    } else {
      new import_obsidian11.Notice(`\u5DF2\u662F\u6700\u65B0\u7248\u672C ${info.currentVersion}`);
    }
    return info;
  }
  async doUpdate() {
    if (!this.updateInfo || !this.updateInfo.hasUpdate) {
      new import_obsidian11.Notice("\u6CA1\u6709\u53EF\u7528\u7684\u66F4\u65B0");
      return false;
    }
    const adapter = this.app.vault.adapter;
    if (!(adapter instanceof import_obsidian11.FileSystemAdapter)) {
      new import_obsidian11.Notice("\u4EC5\u652F\u6301\u684C\u9762\u7AEF\u66F4\u65B0");
      return false;
    }
    const vaultBase = adapter.getBasePath();
    const manifestDir = this.manifest.dir || "";
    if (!vaultBase || !manifestDir) {
      new import_obsidian11.Notice("\u65E0\u6CD5\u786E\u5B9A\u63D2\u4EF6\u76EE\u5F55");
      return false;
    }
    const pluginDir = path4.join(vaultBase, manifestDir);
    return performUpdate(pluginDir, this.updateInfo.assetUrls, (msg) => {
      new import_obsidian11.Notice(msg);
    });
  }
  initStatusBar() {
    const item = this.addStatusBarItem();
    this.statusBar.mount(item);
    item.addEventListener("click", () => {
      this.openChatView();
    });
  }
  initAutoSync() {
    if (!this.settings.autoSync)
      return;
    const intervalMs = this.settings.syncIntervalMinutes * 60 * 1e3;
    this.autoSyncTimer = window.setInterval(() => {
      if (!this.pollerRunning && this.ilinkAuth.isAuthenticated) {
        this.startPoller();
      }
    }, intervalMs);
  }
  resetAutoSyncTimer() {
    this.stopAutoSync();
    if (this.settings.autoSync) {
      this.initAutoSync();
    }
  }
  stopAutoSync() {
    if (this.autoSyncTimer !== null) {
      window.clearInterval(this.autoSyncTimer);
      this.autoSyncTimer = null;
    }
  }
  async startPoller() {
    if (this.pollerRunning) {
      new import_obsidian11.Notice("\u5FAE\u4FE1\u6D88\u606F\u76D1\u542C\u5DF2\u5728\u8FD0\u884C\u4E2D");
      return;
    }
    if (!this.ilinkAuth.isAuthenticated) {
      new import_obsidian11.Notice("\u8BF7\u5148\u626B\u7801\u767B\u5F55\u5FAE\u4FE1");
      return;
    }
    const token = this.ilinkAuth.currentToken;
    const baseUrl = this.ilinkAuth.currentBaseUrl;
    this.poller = new ILinkPoller();
    this.poller.setMessageHandler(async (msg) => {
      if (this.messageHandler) {
        await this.messageHandler.handleMessage(msg);
      }
      if (this.chatView) {
        this.chatView.addMessage(msg);
      }
    });
    this.poller.setErrorHandler((error) => {
      console.error("[WeChat Sync] \u8F6E\u8BE2\u9519\u8BEF:", error);
    });
    this.poller.setStatusHandler((status) => {
      console.log("[WeChat Sync] \u72B6\u6001:", status);
      if (status === "polling") {
        this.pollerRunning = true;
        this.statusBar.setStatus("polling");
      } else if (status === "connected") {
        this.pollerRunning = true;
        this.statusBar.setStatus("polling");
      } else if (status === "stopped" || status === "error") {
        this.pollerRunning = false;
        this.statusBar.setStatus(status === "error" ? "error" : "authed");
      } else if (status === "session_expired") {
        this.pollerRunning = false;
        this.statusBar.setStatus("error");
      } else if (status === "reconnecting") {
        this.statusBar.setStatus("polling");
      }
      this.app.workspace.trigger("we-chat-sync:status", status);
    });
    this.pollerRunning = true;
    this.statusBar.setStatus("polling");
    new import_obsidian11.Notice("\u5F00\u59CB\u76D1\u542C\u5FAE\u4FE1\u6D88\u606F");
    this.poller.start(token, baseUrl).catch((e) => {
      console.error("[WeChat Sync] \u8F6E\u8BE2\u5F02\u5E38\u9000\u51FA:", e);
      this.pollerRunning = false;
      this.statusBar.setStatus("error");
    });
  }
  stopPoller() {
    if (this.poller) {
      this.poller.stop();
      this.poller = null;
    }
    this.pollerRunning = false;
    this.statusBar.setStatus("authed");
    new import_obsidian11.Notice("\u5DF2\u505C\u6B62\u76D1\u542C\u5FAE\u4FE1\u6D88\u606F");
  }
  showReplyModal() {
    var _a;
    if (!this.sender) {
      new import_obsidian11.Notice("\u8BF7\u5148\u767B\u5F55\u5FAE\u4FE1");
      return;
    }
    const tokens = this.messageHandler ? Array.from(((_a = this.messageHandler.contextTokens) == null ? void 0 : _a.values()) || []) : [];
    const modal = new WeChatReplyModal(this.app, tokens);
    modal.setOnSend(async (contextToken, text, toUserId) => {
      if (this.noteExporter) {
        await this.noteExporter.sendTextReply(contextToken, text, toUserId);
      }
    });
    modal.open();
  }
  async sendCurrentNote() {
    var _a;
    if (!this.sender) {
      new import_obsidian11.Notice("\u8BF7\u5148\u767B\u5F55\u5FAE\u4FE1");
      return;
    }
    const tokens = this.messageHandler ? Array.from(((_a = this.messageHandler.contextTokens) == null ? void 0 : _a.values()) || []) : [];
    if (tokens.length === 0) {
      new import_obsidian11.Notice("\u6682\u65E0\u53EF\u7528\u7684\u5FAE\u4FE1\u4F1A\u8BDD\uFF0C\u8BF7\u5148\u6536\u5230\u6D88\u606F\u540E\u518D\u56DE\u590D");
      return;
    }
    const modal = new WeChatReplyModal(this.app, tokens);
    modal.setOnSend(async (contextToken, _text, toUserId) => {
      if (this.noteExporter) {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile && activeFile.extension === "md") {
          await this.noteExporter.sendNoteToWechat(activeFile, contextToken, toUserId);
        } else {
          new import_obsidian11.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u6587\u4EF6");
        }
      }
    });
    modal.open();
  }
  async sendCurrentNoteReply() {
    if (!this.sender) {
      new import_obsidian11.Notice("\u8BF7\u5148\u767B\u5F55\u5FAE\u4FE1");
      return;
    }
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile || activeFile.extension !== "md") {
      new import_obsidian11.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u6587\u4EF6");
      return;
    }
    if (this.noteExporter) {
      await this.noteExporter.sendNoteToLatestContext(activeFile);
    }
  }
  async syncAll() {
    if (!this.syncEngine)
      return;
    this.statusBar.setSyncing();
    const modal = new SyncModal(this.app, {
      total: 0,
      current: 0,
      currentFile: "",
      phase: "scanning",
      errors: []
    });
    modal.open();
    this.syncEngine.setProgressCallback((progress) => {
      modal.updateProgress(progress);
      this.statusBar.updateProgress(progress);
    });
    const result = await this.syncEngine.syncAll();
    if (result.phase === "error") {
      this.statusBar.setError(result.errors.map((e) => e.message).join("; "));
    } else {
      this.statusBar.setIdle();
    }
  }
  async pushLocalChanges() {
    if (!this.syncEngine)
      return;
    this.statusBar.setSyncing();
    this.syncEngine.setProgressCallback((progress) => {
      this.statusBar.updateProgress(progress);
    });
    const result = await this.syncEngine.pushLocalChanges();
    if (result.phase === "error") {
      this.statusBar.setError(result.errors.map((e) => e.message).join("; "));
    } else {
      this.statusBar.setIdle();
      new import_obsidian11.Notice("\u672C\u5730\u4FEE\u6539\u5DF2\u63A8\u9001");
    }
  }
  onFileModified(file) {
    if (!this.settings.enableBidirectionalSync)
      return;
    if (!this.syncEngine)
      return;
    const syncFolder = this.settings.syncFolder;
    if (!file.path.startsWith(syncFolder))
      return;
    const cache = this.app.metadataCache.getFileCache(file);
    const frontmatter = cache == null ? void 0 : cache.frontmatter;
    if ((frontmatter == null ? void 0 : frontmatter.wechat_msg_id) || (frontmatter == null ? void 0 : frontmatter.wechat_session)) {
      this.syncEngine.syncSingleFile(file).catch((e) => {
        console.error("[WeChat Sync] \u6587\u4EF6\u540C\u6B65\u5931\u8D25:", e);
      });
    }
  }
  async showQRLogin() {
    var _a;
    try {
      new import_obsidian11.Notice("\u6B63\u5728\u83B7\u53D6\u5FAE\u4FE1\u4E8C\u7EF4\u7801...");
      const result = await this.ilinkAuth.fetchQRCode();
      const modal = new QRCodeModal(this.app);
      modal.setQRCode(result.qrcodeUrl);
      modal.open();
      const authResult = await this.ilinkAuth.loginWithPolling(
        result.qrcode,
        (status) => {
          modal.setStatus(status);
        }
      );
      modal.close();
      await this.saveAuthData(authResult);
      this.sender = new ILinkSender(authResult.token, authResult.baseUrl);
      (_a = this.noteExporter) == null ? void 0 : _a.setSender(this.sender);
      this.statusBar.setStatus("authed");
      await this.startPoller();
      new import_obsidian11.Notice("\u5FAE\u4FE1\u767B\u5F55\u6210\u529F\uFF01\u5DF2\u5F00\u59CB\u76D1\u542C\u6D88\u606F");
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      console.error("[WeChat Sync] \u767B\u5F55\u5931\u8D25:", msg);
      new import_obsidian11.Notice(`\u767B\u5F55\u5931\u8D25: ${msg}`);
    }
  }
  getVaultPath() {
    const adapter = this.app.vault.adapter;
    if (adapter instanceof import_obsidian11.FileSystemAdapter) {
      return adapter.getBasePath();
    }
    return os2.homedir();
  }
};
